export interface KanjiRadical {
  id: string;
  char: string;
  hanViet: string;
  meaningVi: string;
  meaningEn: string;
  strokes: number;
  strokeGuide: string;
  strokePaths: string[];
  exampleKanji: Array<{ char: string; pinyin: string; hanViet: string; meaning: string }>;
}

export const KANJI_RADICALS: KanjiRadical[] = [
  // --- HÀNG 1 ---
  {
    id: "rad-chu",
    char: "丶",
    hanViet: "Chấm chủ",
    meaningVi: "Nét chấm trên đầu chữ, biểu thị điểm nhấn hoặc ngọn lửa nhỏ.",
    meaningEn: "Dot / Point",
    strokes: 1,
    strokeGuide: "Nét chấm nghiêng nhẹ từ trên trái xuống dưới phải.",
    strokePaths: ["M 48 30 C 52 38, 58 48, 62 55"],
    exampleKanji: [
      { char: "主", pinyin: "zhǔ", hanViet: "Chủ", meaning: "Chủ nhân, chính" },
      { char: "丸", pinyin: "wán", hanViet: "Hoàn", meaning: "Tròn, viên thuốc" },
    ],
  },
  {
    id: "rad-phiet",
    char: "丿",
    hanViet: "Nét phiệt",
    meaningVi: "Nét phẩy vuốt nhẹ từ trên phải xuống dưới trái.",
    meaningEn: "Slash / Sweep",
    strokes: 1,
    strokeGuide: "Kéo nét phẩy cong từ trên xuống dưới về phía trái.",
    strokePaths: ["M 65 20 C 58 45, 42 70, 25 85"],
    exampleKanji: [
      { char: "乃", pinyin: "nǎi", hanViet: "Nãi", meaning: "Bèn, là" },
      { char: "久", pinyin: "jiǔ", hanViet: "Cửu", meaning: "Lâu dài" },
    ],
  },
  {
    id: "rad-con",
    char: "丨",
    hanViet: "Nét cổn",
    meaningVi: "Nét sổ thẳng đứng từ trên xuống dưới.",
    meaningEn: "Vertical Line",
    strokes: 1,
    strokeGuide: "Kéo nét sổ thẳng đứng từ trên xuống dưới.",
    strokePaths: ["M 50 15 L 50 85"],
    exampleKanji: [
      { char: "中", pinyin: "zhōng", hanViet: "Trung", meaning: "Ở giữa, Trung Quốc" },
      { char: "十", pinyin: "shí", hanViet: "Thập", meaning: "Số 10" },
    ],
  },
  {
    id: "rad-quyet",
    char: "亅",
    hanViet: "Nét quyết",
    meaningVi: "Nét móc đứng, sổ từ trên xuống rồi hất móc lên trái.",
    meaningEn: "Hook",
    strokes: 1,
    strokeGuide: "Kéo nét sổ đứng từ trên xuống rồi hất nhọn móc sang trái.",
    strokePaths: ["M 50 15 L 50 80 C 45 83, 40 80, 35 75"],
    exampleKanji: [
      { char: "了", pinyin: "liǎo", hanViet: "Liễu", meaning: "Xong, rồi" },
      { char: "予", pinyin: "yǔ", hanViet: "Dự", meaning: "Sẵn, dự báo" },
    ],
  },
  {
    id: "rad-dao-dung",
    char: "刂",
    hanViet: "Bộ đao (đao đứng)",
    meaningVi: "Con dao, thanh kiếm (thường đứng ở bên phải chữ).",
    meaningEn: "Knife (standing)",
    strokes: 2,
    strokeGuide: "Nét 1: sổ ngắn trái; Nét 2: sổ dài móc lên phải.",
    strokePaths: ["M 38 25 L 38 60", "M 62 15 L 62 80 C 58 83, 52 80, 48 76"],
    exampleKanji: [
      { char: "切", pinyin: "qiē", hanViet: "Thiết", meaning: "Cắt (切ります)" },
      { char: "前", pinyin: "qián", hanViet: "Tiền", meaning: "Trước, phía trước" },
    ],
  },

  // --- HÀNG 2 ---
  {
    id: "rad-dau",
    char: "亠",
    hanViet: "Bộ đầu",
    meaningVi: "Mái nhà không có vách, nắp che phủ phía trên.",
    meaningEn: "Lid / Head cover",
    strokes: 2,
    strokeGuide: "Nét 1: chấm giữa; Nét 2: ngang dài phủ dưới.",
    strokePaths: ["M 50 20 L 50 35", "M 20 40 L 80 40"],
    exampleKanji: [
      { char: "京", pinyin: "jīng", hanViet: "Kinh", meaning: "Kinh đô (東京)" },
      { char: "高", pinyin: "gāo", hanViet: "Cao", meaning: "Cao, đắt (高い)" },
    ],
  },
  {
    id: "rad-mien",
    char: "宀",
    hanViet: "Bộ miên",
    meaningVi: "Mái nhà có vách che phủ kín xung quanh.",
    meaningEn: "Roof",
    strokes: 3,
    strokeGuide: "Nét 1: chấm đỉnh; Nét 2: phẩy đứng trái; Nét 3: ngang gập phải.",
    strokePaths: ["M 50 15 L 50 28", "M 28 32 L 24 55", "M 25 35 L 75 35 L 75 55"],
    exampleKanji: [
      { char: "家", pinyin: "jiā", hanViet: "Gia", meaning: "Nhà, gia đình" },
      { char: "安", pinyin: "ān", hanViet: "An", meaning: "An toàn, rẻ (安い)" },
    ],
  },
  {
    id: "rad-mich",
    char: "冖",
    hanViet: "Bộ mịch",
    meaningVi: "Trùm che, màng phủ, khăn trùm trên đầu.",
    meaningEn: "Cover / Canopy",
    strokes: 2,
    strokeGuide: "Nét 1: phẩy đứng trái; Nét 2: ngang gập đè lên.",
    strokePaths: ["M 25 30 L 22 60", "M 23 35 L 75 35 L 75 60"],
    exampleKanji: [
      { char: "写", pinyin: "xiě", hanViet: "Tả", meaning: "Chụp ảnh (写真)" },
      { char: "冠", pinyin: "guān", hanViet: "Quan", meaning: "Vương miện" },
    ],
  },

  // --- HÀNG 3 ---
  {
    id: "rad-nhan-dung",
    char: "亻",
    hanViet: "Nhân đứng",
    meaningVi: "Con người (dạng nhân đứng phía bên trái chữ).",
    meaningEn: "Person (standing)",
    strokes: 2,
    strokeGuide: "Nét 1: phẩy từ trên xuống trái; Nét 2: sổ thẳng đứng xuống dưới.",
    strokePaths: ["M 55 20 C 45 40, 32 60, 20 75", "M 42 42 L 42 88"],
    exampleKanji: [
      { char: "休", pinyin: "xiū", hanViet: "Hưu", meaning: "Nghỉ ngơi (休みます)" },
      { char: "体", pinyin: "tǐ", hanViet: "Thể", meaning: "Cơ thể" },
    ],
  },
  {
    id: "rad-nhan-nam",
    char: "𠂉",
    hanViet: "Nhân nằm",
    meaningVi: "Con người (dạng nằm/nghiêng ở đầu trên chữ).",
    meaningEn: "Person (lying / top)",
    strokes: 2,
    strokeGuide: "Nét 1: phẩy nằm trên; Nét 2: nét ngang móc/gập nghiêng.",
    strokePaths: ["M 65 20 C 50 30, 35 45, 25 55", "M 32 35 L 78 35"],
    exampleKanji: [
      { char: "午", pinyin: "wǔ", hanViet: "Ngọ", meaning: "Buổi trưa (午前/午後)" },
      { char: "年", pinyin: "nián", hanViet: "Niên", meaning: "Năm (今年)" },
    ],
  },
  {
    id: "rad-nhan-non",
    char: "人",
    hanViet: "Nhân nón",
    meaningVi: "Con người (xòe hình mái nón che trên đầu chữ).",
    meaningEn: "Person (roof / hat)",
    strokes: 2,
    strokeGuide: "Nét 1: phẩy trái rộng; Nét 2: mác phải rộng cân xứng.",
    strokePaths: ["M 50 18 C 40 40, 28 65, 18 82", "M 48 35 C 58 50, 72 70, 85 85"],
    exampleKanji: [
      { char: "人", pinyin: "rén", hanViet: "Nhân", meaning: "Người" },
      { char: "今", pinyin: "jīn", hanViet: "Kim", meaning: "Bây giờ (今)" },
    ],
  },
  {
    id: "rad-nhan-di",
    char: "儿",
    hanViet: "Nhân đi (chân người)",
    meaningVi: "Đôi chân con người đang bước đi phía dưới chữ.",
    meaningEn: "Person walking / Legs",
    strokes: 2,
    strokeGuide: "Nét 1: phẩy đứng trái; Nét 2: sổ cong móc hất sang phải.",
    strokePaths: ["M 40 30 C 35 55, 28 75, 18 88", "M 60 30 L 60 70 C 60 80, 68 85, 80 85"],
    exampleKanji: [
      { char: "元", pinyin: "yuán", hanViet: "Nguyên", meaning: "Khỏe mạnh (元気)" },
      { char: "先", pinyin: "xiān", hanViet: "Tiên", meaning: "Trước, thầy giáo (先生)" },
    ],
  },

  // --- HÀNG 4 ---
  {
    id: "rad-tam",
    char: "彡",
    hanViet: "Bộ tam",
    meaningVi: "Lông tóc, hoa văn rực rỡ hoặc bóng râm trang trí 3 nét phẩy.",
    meaningEn: "Hair / 3 Strokes",
    strokes: 3,
    strokeGuide: "Vẽ 3 nét phẩy song song xuôi từ trên xuống dưới về phía trái.",
    strokePaths: ["M 65 20 C 50 30, 40 40, 30 50", "M 68 42 C 53 52, 43 62, 33 72", "M 72 65 C 57 75, 47 85, 35 93"],
    exampleKanji: [
      { char: "形", pinyin: "xíng", hanViet: "Hình", meaning: "Hình dáng" },
      { char: "影", pinyin: "yǐng", hanViet: "Ảnh", meaning: "Bóng dáng, hình ảnh" },
    ],
  },
  {
    id: "rad-sach",
    char: "攵",
    hanViet: "Bộ sách / Phộc",
    meaningVi: "Đánh khẽ, gõ nhẹ, hành động tác động nhẹ nhàng.",
    meaningEn: "Whip / Strike / Action",
    strokes: 4,
    strokeGuide: "Nét 1: phẩy trên; Nét 2: ngang gập; Nét 3: phẩy trái; Nét 4: mác phải.",
    strokePaths: ["M 55 18 C 45 28, 38 35, 30 42", "M 32 32 L 72 32 L 60 52", "M 52 45 C 45 60, 35 75, 20 88", "M 48 52 C 58 65, 72 78, 85 88"],
    exampleKanji: [
      { char: "教", pinyin: "jiào", hanViet: "Giáo", meaning: "Dạy học (教えます)" },
      { char: "政", pinyin: "zhèng", hanViet: "Chính", meaning: "Chính trị" },
    ],
  },
  {
    id: "rad-tam-dung",
    char: "忄",
    hanViet: "Bộ tâm (tâm đứng)",
    meaningVi: "Trái tim, tâm trí, cảm xúc (đứng ở bên trái chữ).",
    meaningEn: "Heart (standing)",
    strokes: 3,
    strokeGuide: "Nét 1: chấm phẩy trái; Nét 2: chấm phải; Nét 3: sổ dài giữa xuyên xuống.",
    strokePaths: ["M 25 38 C 22 48, 18 58, 15 65", "M 40 32 C 43 40, 45 48, 48 55", "M 30 15 L 30 88"],
    exampleKanji: [
      { char: "忙", pinyin: "máng", hanViet: "Mang", meaning: "Bận rộn (忙しい)" },
      { char: "情", pinyin: "qíng", hanViet: "Tình", meaning: "Tình cảm" },
    ],
  },
  {
    id: "rad-phu",
    char: "阝",
    hanViet: "Bộ phụ (bên trái)",
    meaningVi: "Gò đất, đồi núi, địa hình cao (đứng bên trái chữ).",
    meaningEn: "Hill / Mound (left side)",
    strokes: 3,
    strokeGuide: "Nét 1: ngang cong gập; Nét 2: cong tròn móc; Nét 3: sổ đứng dài.",
    strokePaths: ["M 28 20 L 48 20 C 55 20, 55 35, 42 40 C 58 45, 58 62, 45 65 C 38 67, 30 65, 25 62", "M 28 20 L 28 88"],
    exampleKanji: [
      { char: "阪", pinyin: "bǎn", hanViet: "Phản", meaning: "Độ dốc (大阪 - Osaka)" },
      { char: "院", pinyin: "yuàn", hanViet: "Viện", meaning: "Bệnh viện (病院)" },
    ],
  },
  {
    id: "rad-ap",
    char: "阝",
    hanViet: "Bộ ấp (bên phải)",
    meaningVi: "Thành quách, vùng đất, xóm làng (đứng bên phải chữ).",
    meaningEn: "City / Town (right side)",
    strokes: 3,
    strokeGuide: "Nét 1: ngang cong gập; Nét 2: cong tròn móc; Nét 3: sổ đứng dài bên phải.",
    strokePaths: ["M 62 20 L 82 20 C 89 20, 89 35, 76 40 C 92 45, 92 62, 79 65 C 72 67, 64 65, 59 62", "M 62 20 L 62 88"],
    exampleKanji: [
      { char: "部", pinyin: "bù", hanViet: "Bộ", meaning: "Bộ phận, căn phòng (部屋)" },
      { char: "都", pinyin: "dū", hanViet: "Đô", meaning: "Đô thành (京都)" },
    ],
  },
  {
    id: "rad-tiet",
    char: "卩",
    hanViet: "Bộ tiết",
    meaningVi: "Đốt trúc, con dấu, hình dáng người quỳ gối.",
    meaningEn: "Seal / Knee joint",
    strokes: 2,
    strokeGuide: "Nét 1: ngang gập cong đứng; Nét 2: sổ đứng xiên.",
    strokePaths: ["M 30 25 L 65 25 L 65 55 C 65 70, 58 82, 45 88", "M 38 25 L 38 75"],
    exampleKanji: [
      { char: "印", pinyin: "yìn", hanViet: "Ấn", meaning: "Con dấu (印鑑)" },
      { char: "危", pinyin: "wēi", hanViet: "Nguy", meaning: "Nguy hiểm (危ない)" },
    ],
  },

  // --- HÀNG 5 ---
  {
    id: "rad-bang",
    char: "冫",
    hanViet: "2 chấm băng",
    meaningVi: "Nước đá, băng giá, cái lạnh buốt.",
    meaningEn: "Ice (2 dots)",
    strokes: 2,
    strokeGuide: "Nét 1: chấm hất nhẹ dưới trái; Nét 2: phẩy hất đứng trên.",
    strokePaths: ["M 32 30 C 38 35, 42 42, 45 48", "M 28 65 C 38 65, 48 58, 55 50"],
    exampleKanji: [
      { char: "冷", pinyin: "lěng", hanViet: "Lãnh", meaning: "Lạnh buốt (冷たい)" },
      { char: "冬", pinyin: "dōng", hanViet: "Đông", meaning: "Mùa đông (冬)" },
    ],
  },
  {
    id: "rad-thuy",
    char: "氵",
    hanViet: "3 chấm thủy",
    meaningVi: "Nước, dòng sông, hồ nước, chất lỏng.",
    meaningEn: "Water (3 dots)",
    strokes: 3,
    strokeGuide: "Nét 1: chấm trên; Nét 2: chấm giữa; Nét 3: hất nhẹ dưới lên.",
    strokePaths: ["M 35 22 C 40 28, 42 35, 45 40", "M 30 46 C 36 50, 40 56, 42 60", "M 25 78 C 32 74, 45 62, 52 54"],
    exampleKanji: [
      { char: "水", pinyin: "shuǐ", hanViet: "Thủy", meaning: "Nước (水)" },
      { char: "海", pinyin: "hǎi", hanViet: "Hải", meaning: "Biển (海)" },
    ],
  },
  {
    id: "rad-hoa",
    char: "灬",
    hanViet: "4 chấm hỏa",
    meaningVi: "Ngọn lửa, sức nóng lò sưởi (nằm ở đáy chữ).",
    meaningEn: "Fire (4 dots bottom)",
    strokes: 4,
    strokeGuide: "Xếp 4 chấm từ trái sang phải ở chân chữ.",
    strokePaths: [
      "M 22 75 C 20 80, 18 85, 15 88",
      "M 40 75 C 41 80, 42 85, 42 88",
      "M 60 75 C 61 80, 63 85, 64 88",
      "M 80 75 C 82 80, 85 85, 88 88",
    ],
    exampleKanji: [
      { char: "黒", pinyin: "hēi", hanViet: "Hắc", meaning: "Màu đen (黒い)" },
      { char: "点", pinyin: "diǎn", hanViet: "Điểm", meaning: "Điểm số, chấm" },
    ],
  },

  // --- HÀNG 6 ---
  {
    id: "rad-han",
    char: "厂",
    hanViet: "Bộ hán",
    meaningVi: "Sườn núi, vách đá nhô ra.",
    meaningEn: "Cliff",
    strokes: 2,
    strokeGuide: "Nét 1: ngang trên dài; Nét 2: phẩy vuốt dài bên trái.",
    strokePaths: ["M 22 25 L 82 25", "M 28 25 C 26 50, 20 72, 12 88"],
    exampleKanji: [
      { char: "原", pinyin: "yuán", hanViet: "Nguyên", meaning: "Cánh đồng, nguồn cội" },
      { char: "厚", pinyin: "hòu", hanViet: "Hậu", meaning: "Dày dặn" },
    ],
  },
  {
    id: "rad-nghiem",
    char: "广",
    hanViet: "Bộ nghiêm",
    meaningVi: "Tòa nhà, ngôi nhà tựa vào sườn núi, hiên nhà rộng.",
    meaningEn: "Dotted cliff / House on hill",
    strokes: 3,
    strokeGuide: "Nét 1: chấm đỉnh; Nét 2: ngang dài; Nét 3: phẩy vuốt trái.",
    strokePaths: ["M 50 15 L 50 28", "M 22 28 L 82 28", "M 28 28 C 26 52, 20 74, 12 88"],
    exampleKanji: [
      { char: "店", pinyin: "diàn", hanViet: "Điếm", meaning: "Cửa hàng (店)" },
      { char: "広", pinyin: "guǎng", hanViet: "Quảng", meaning: "Rộng rãi (広い)" },
    ],
  },
  {
    id: "rad-nach",
    char: "疒",
    hanViet: "Bộ nạch",
    meaningVi: "Bệnh tật, ốm đau, thương tật con người.",
    meaningEn: "Sickness / Disease",
    strokes: 5,
    strokeGuide: "Nét 1: chấm đỉnh; Nét 2: ngang; Nét 3: phẩy trái; Nét 4: chấm trái; Nét 5: phẩy dưới.",
    strokePaths: [
      "M 50 12 L 50 22",
      "M 25 22 L 80 22",
      "M 30 22 C 28 50, 22 72, 14 88",
      "M 15 40 C 18 45, 20 50, 22 55",
      "M 18 60 L 30 60",
    ],
    exampleKanji: [
      { char: "病", pinyin: "bìng", hanViet: "Bệnh", meaning: "Bệnh tật (病院)" },
      { char: "痛", pinyin: "tòng", hanViet: "Thống", meaning: "Đau đớn (痛い)" },
    ],
  },
  {
    id: "rad-trao",
    char: "爫",
    hanViet: "Bộ trảo",
    meaningVi: "Móng nốt, bàn tay cào vuốt từ trên xuống.",
    meaningEn: "Claw / Hand from top",
    strokes: 4,
    strokeGuide: "Nét 1: phẩy nằm trên; Nét 2, 3, 4: ba phẩy song song dưới.",
    strokePaths: ["M 70 20 C 55 28, 38 35, 25 40", "M 32 45 L 22 75", "M 50 42 L 45 75", "M 70 40 L 75 75"],
    exampleKanji: [
      { char: "采", pinyin: "cǎi", hanViet: "Thải", meaning: "Hái lượm" },
      { char: "受", pinyin: "shòu", hanViet: "Thụ", meaning: "Nhận (受けます)" },
    ],
  },
  {
    id: "rad-truc",
    char: "⺮",
    hanViet: "Bộ trúc",
    meaningVi: "Cây tre, cây trúc, các đồ làm bằng tre.",
    meaningEn: "Bamboo",
    strokes: 6,
    strokeGuide: "Hai cụm nét tre nhỏ đặt cân xứng ở đỉnh chữ.",
    strokePaths: [
      "M 35 18 L 22 30",
      "M 20 32 L 45 32",
      "M 32 32 L 28 45",
      "M 70 18 L 57 30",
      "M 55 32 L 85 32",
      "M 68 32 L 68 45",
    ],
    exampleKanji: [
      { char: "竹", pinyin: "zhú", hanViet: "Trúc", meaning: "Cây tre" },
      { char: "答", pinyin: "dá", hanViet: "Đáp", meaning: "Trả lời (答え)" },
    ],
  },

  // --- HÀNG 7 ---
  {
    id: "rad-khu",
    char: "厶",
    hanViet: "Bộ khư",
    meaningVi: "Riêng tư, bí mật, cá nhân.",
    meaningEn: "Private / Selfish",
    strokes: 2,
    strokeGuide: "Nét 1: phẩy gấp ngang; Nét 2: chấm hất phải.",
    strokePaths: ["M 50 20 L 25 60 L 75 60", "M 55 45 C 65 52, 75 62, 85 70"],
    exampleKanji: [
      { char: "私", pinyin: "sī", hanViet: "Tư", meaning: "Tôi, riêng tư (私)" },
      { char: "公", pinyin: "gōng", hanViet: "Công", meaning: "Công cộng (公園)" },
    ],
  },
  {
    id: "rad-yeu",
    char: "幺",
    hanViet: "Bộ yêu",
    meaningVi: "Nhỏ bé, sợi chỉ nhỏ vụn vặt.",
    meaningEn: "Short thread / Tiny",
    strokes: 3,
    strokeGuide: "Nét 1: phẩy gập 1; Nét 2: phẩy gập 2; Nét 3: chấm dưới.",
    strokePaths: ["M 50 18 L 32 38 L 55 45", "M 55 45 L 28 68 L 68 68", "M 48 70 C 58 75, 68 80, 75 85"],
    exampleKanji: [
      { char: "幼", pinyin: "yòu", hanViet: "Ấu", meaning: "Thơ ấu, trẻ con" },
      { char: "幽", pinyin: "yōu", hanViet: "U", meaning: "U uất, sâu thẳm" },
    ],
  },
  {
    id: "rad-to",
    char: "糸",
    hanViet: "Bộ tơ (mịch)",
    meaningVi: "Sợi tơ, dây dợ, tơ lụa, sự liên kết.",
    meaningEn: "Silk / Thread",
    strokes: 6,
    strokeGuide: "Cụm tơ trên gập Z, dưới 3 chấm xòe.",
    strokePaths: [
      "M 48 15 L 32 30 L 52 35",
      "M 52 35 L 28 52 L 68 52",
      "M 48 52 L 48 78",
      "M 28 65 C 24 72, 20 78, 16 82",
      "M 48 65 C 55 72, 62 78, 68 82",
      "M 72 65 C 78 72, 82 78, 86 82",
    ],
    exampleKanji: [
      { char: "紙", pinyin: "zhǐ", hanViet: "Chỉ", meaning: "Tờ giấy (紙)" },
      { char: "線", pinyin: "xiàn", hanViet: "Tuyến", meaning: "Tuyến đường, sợi dây" },
    ],
  },

  // --- HÀNG 8 ---
  {
    id: "rad-huu",
    char: "又",
    hanViet: "Bộ hựu",
    meaningVi: "Bàn tay phải, lặp lại, lại nữa.",
    meaningEn: "Right hand / Again",
    strokes: 2,
    strokeGuide: "Nét 1: ngang gập phẩy; Nét 2: mác chéo phải.",
    strokePaths: ["M 28 32 L 72 32 L 35 82", "M 32 45 C 48 58, 65 72, 85 85"],
    exampleKanji: [
      { char: "友", pinyin: "yǒu", hanViet: "Hữu", meaning: "Bạn bè (友達)" },
      { char: "取", pinyin: "qǔ", hanViet: "Thủ", meaning: "Lấy (取ります)" },
    ],
  },
  {
    id: "rad-truy",
    char: "攵",
    hanViet: "Bộ truy / Phộc",
    meaningVi: "Bước đi chậm rãi, theo sau, tác động lực.",
    meaningEn: "Slow walk / Strike",
    strokes: 4,
    strokeGuide: "Nét 1: phẩy trên; Nét 2: ngang gập; Nét 3: phẩy trái; Nét 4: mác phải.",
    strokePaths: ["M 55 18 C 45 28, 38 35, 30 42", "M 32 32 L 72 32 L 60 52", "M 52 45 C 45 60, 35 75, 20 88", "M 48 52 C 58 65, 72 78, 85 88"],
    exampleKanji: [
      { char: "夏", pinyin: "xià", hanViet: "Hạ", meaning: "Mùa hè (夏)" },
      { char: "変", pinyin: "biàn", hanViet: "Biến", meaning: "Thay đổi (大変)" },
    ],
  },
  {
    id: "rad-phoc",
    char: "支",
    hanViet: "Bộ phộc / Chi",
    meaningVi: "Cành cây, tay cầm gậy nâng đỡ.",
    meaningEn: "Branch / Support",
    strokes: 4,
    strokeGuide: "Nét 1: thập trên; Nét 2: hựu dưới.",
    strokePaths: ["M 25 30 L 75 30", "M 50 15 L 50 48", "M 30 48 L 72 48 L 35 88", "M 32 58 C 48 68, 65 78, 85 88"],
    exampleKanji: [
      { char: "支", pinyin: "zhī", hanViet: "Chi", meaning: "Chi nhánh, hỗ trợ" },
      { char: "技", pinyin: "jì", hanViet: "Kỹ", meaning: "Kỹ năng, kỹ thuật" },
    ],
  },
  {
    id: "rad-chi-heo",
    char: "彐",
    hanViet: "Bộ chi (đầu heo)",
    meaningVi: "Đầu con heo, hình bàn tay nắm.",
    meaningEn: "Pig's head / Hand",
    strokes: 3,
    strokeGuide: "Nét 1: khung gập trên; Nét 2: ngang giữa; Nét 3: ngang đáy.",
    strokePaths: ["M 30 25 L 75 25 L 75 80 L 30 80", "M 30 52 L 70 52", "M 30 80 L 75 80"],
    exampleKanji: [
      { char: "帰", pinyin: "guī", hanViet: "Quy", meaning: "Trở về (帰ります)" },
      { char: "尋", pinyin: "xún", hanViet: "Tầm", meaning: "Hỏi thăm, tìm kiếm" },
    ],
  },

  // --- HÀNG 9 ---
  {
    id: "rad-khau",
    char: "口",
    hanViet: "Bộ khẩu",
    meaningVi: "Cái miệng, lời nói, lối ra vào.",
    meaningEn: "Mouth",
    strokes: 3,
    strokeGuide: "Nét 1: sổ trái; Nét 2: ngang gập xuống phải; Nét 3: ngang đáy đóng ô.",
    strokePaths: ["M 25 25 L 25 78", "M 25 25 L 75 25 L 75 78", "M 25 78 L 75 78"],
    exampleKanji: [
      { char: "口", pinyin: "kǒu", hanViet: "Khẩu", meaning: "Miệng, cổng (出口)" },
      { char: "古", pinyin: "gǔ", hanViet: "Cổ", meaning: "Cổ kính, cũ (古い)" },
    ],
  },
  {
    id: "rad-vi",
    char: "囗",
    hanViet: "Bộ vi",
    meaningVi: "Vây quanh, phạm vi bao bọc bên ngoài.",
    meaningEn: "Enclosure (large box)",
    strokes: 3,
    strokeGuide: "Ô vuông to bao bọc toàn bộ thành phần bên trong.",
    strokePaths: ["M 18 18 L 18 85", "M 18 18 L 82 18 L 82 85", "M 18 85 L 82 85"],
    exampleKanji: [
      { char: "国", pinyin: "guó", hanViet: "Quốc", meaning: "Đất nước (外国)" },
      { char: "園", pinyin: "yuán", hanViet: "Viên", meaning: "Công viên (公園)" },
    ],
  },
  {
    id: "rad-quynh",
    char: "冂",
    hanViet: "Bộ quynh",
    meaningVi: "Vùng biên giới xa xôi, khoảng không rộng bao trùm.",
    meaningEn: "Border / Down box",
    strokes: 2,
    strokeGuide: "Khung chữ U úp ngược mở ở phía dưới.",
    strokePaths: ["M 22 25 L 22 85", "M 22 25 L 78 25 L 78 85"],
    exampleKanji: [
      { char: "同", pinyin: "tóng", hanViet: "Đồng", meaning: "Giống nhau ( me )" },
      { char: "周", pinyin: "zhōu", hanViet: "Chu", meaning: "Chu vi, xung quanh" },
    ],
  },
  {
    id: "rad-ky",
    char: "己",
    hanViet: "Bộ kỷ",
    meaningVi: "Bản thân, góc riêng tư cá nhân.",
    meaningEn: "Self",
    strokes: 3,
    strokeGuide: "Nét 1: ngang gập; Nét 2: ngang; Nét 3: cong móc lên.",
    strokePaths: ["M 30 22 L 70 22 L 35 48", "M 35 48 L 70 48", "M 70 48 L 70 78 C 70 88, 78 88, 85 82"],
    exampleKanji: [
      { char: "己", pinyin: "jǐ", hanViet: "Kỷ", meaning: "Tự bản thân" },
      { char: "記", pinyin: "jì", hanViet: "Ký", meaning: "Ghi chép (日記)" },
    ],
  },

  // --- HÀNG 10 (DƯỚI CÙNG) ---
  {
    id: "rad-moc",
    char: "木",
    hanViet: "Bộ mộc",
    meaningVi: "Cây cối, gỗ, thực vật có thân gỗ.",
    meaningEn: "Tree / Wood",
    strokes: 4,
    strokeGuide: "Nét 1: ngang; Nét 2: sổ giữa; Nét 3: phẩy trái; Nét 4: mác phải.",
    strokePaths: ["M 18 40 L 82 40", "M 50 15 L 50 88", "M 50 40 C 40 58, 28 74, 15 85", "M 50 40 C 60 58, 72 74, 85 85"],
    exampleKanji: [
      { char: "木", pinyin: "mù", hanViet: "Mộc", meaning: "Cây gỗ (木)" },
      { char: "林", pinyin: "lín", hanViet: "Lâm", meaning: "Rừng thưa (林)" },
    ],
  },
  {
    id: "rad-hoa-lua",
    char: "禾",
    hanViet: "Bộ hòa",
    meaningVi: "Cây lúa, ngũ cốc, mùa màng thu hoạch.",
    meaningEn: "Grain / Rice plant",
    strokes: 5,
    strokeGuide: "Như bộ mộc nhưng có thêm nét phẩy nhỏ trên đỉnh.",
    strokePaths: ["M 65 15 C 52 22, 38 26, 28 28", "M 18 48 L 82 48", "M 50 25 L 50 88", "M 50 48 C 40 64, 28 78, 15 86", "M 50 48 C 60 64, 72 78, 85 86"],
    exampleKanji: [
      { char: "私", pinyin: "sī", hanViet: "Tư", meaning: "Tôi (私)" },
      { char: "秋", pinyin: "qiū", hanViet: "Thu", meaning: "Mùa thu (秋)" },
    ],
  },
  {
    id: "rad-thon",
    char: "寸",
    hanViet: "Bộ thốn",
    meaningVi: "Đơn vị đo độ dài (1 thốn ≈ 3.3cm), quy tắc bàn tay.",
    meaningEn: "Inch / Hand measure",
    strokes: 3,
    strokeGuide: "Nét 1: ngang dài; Nét 2: sổ móc đứng; Nét 3: chấm giữa.",
    strokePaths: ["M 20 32 L 80 32", "M 58 15 L 58 78 C 54 86, 46 86, 38 80", "M 38 48 C 42 52, 45 56, 48 60"],
    exampleKanji: [
      { char: "寺", pinyin: "sì", hanViet: "Tự", meaning: "Chùa chiền (金閣寺)" },
      { char: "時", pinyin: "shí", hanViet: "Thời", meaning: "Thời gian (時間)" },
    ],
  },
  {
    id: "rad-thu-dung",
    char: "扌",
    hanViet: "Bộ thủ (tay đứng)",
    meaningVi: "Bàn tay, các hành động dùng tay cầm nắm (bên trái).",
    meaningEn: "Hand (left side)",
    strokes: 3,
    strokeGuide: "Nét 1: ngang ngắn; Nét 2: sổ móc hất trái; Nét 3: hất xiên dưới lên.",
    strokePaths: ["M 25 35 L 68 35", "M 48 18 L 48 78 C 42 86, 35 86, 28 80", "M 22 72 L 62 50"],
    exampleKanji: [
      { char: "持", pinyin: "chí", hanViet: "Trì", meaning: "Cầm nắm (持ちます)" },
      { char: "打", pinyin: "dǎ", hanViet: "Đả", meaning: "Đánh, gõ" },
    ],
  },
  {
    id: "rad-nguu",
    char: "牛",
    hanViet: "Bộ ngưu",
    meaningVi: "Con bò, con trâu, gia súc.",
    meaningEn: "Cow / Ox",
    strokes: 4,
    strokeGuide: "Nét 1: phẩy trên; Nét 2: ngang ngắn; Nét 3: ngang dài; Nét 4: sổ thẳng.",
    strokePaths: ["M 45 15 C 38 22, 30 28, 22 32", "M 28 35 L 72 35", "M 18 55 L 82 55", "M 50 25 L 50 88"],
    exampleKanji: [
      { char: "牛", pinyin: "niú", hanViet: "Ngưu", meaning: "Con bò (牛肉)" },
      { char: "特", pinyin: "tè", hanViet: "Đặc", meaning: "Đặc biệt (特別)" },
    ],
  },
  {
    id: "rad-khuyen-dung",
    char: "犭",
    hanViet: "Bộ khuyển (chó đứng)",
    meaningVi: "Con chó, động vật thú bốn chân (đứng bên trái).",
    meaningEn: "Dog / Animal (standing)",
    strokes: 3,
    strokeGuide: "Nét 1: phẩy cong trái; Nét 2: cong gập hất; Nét 3: phẩy chéo dưới.",
    strokePaths: ["M 48 18 C 38 32, 28 48, 18 62", "M 28 35 C 45 42, 52 58, 38 82", "M 32 50 C 45 62, 58 75, 72 85"],
    exampleKanji: [
      { char: "犬", pinyin: "quǎn", hanViet: "Khuyển", meaning: "Con chó (犬)" },
      { char: "猫", pinyin: "māo", hanViet: "Miêu", meaning: "Con mèo (猫)" },
    ],
  },
  {
    id: "rad-dau-dong",
    char: "斗",
    hanViet: "Bộ đấu",
    meaningVi: "Cái đẩu đong lường, chòm sao Đấu.",
    meaningEn: "Dipper / Measure unit",
    strokes: 4,
    strokeGuide: "Nét 1, 2: hai chấm đứng; Nét 3: ngang dài; Nét 4: sổ xiên phải dài.",
    strokePaths: ["M 28 25 L 28 35", "M 48 20 L 48 32", "M 18 45 L 82 45", "M 62 15 L 62 88"],
    exampleKanji: [
      { char: "斗", pinyin: "dǒu", hanViet: "Đấu", meaning: "Đơn vị đong gạo" },
      { char: "料", pinyin: "liào", hanViet: "Liệu", meaning: "Nguyên liệu (料理)" },
    ],
  },
  {
    id: "rad-hiet",
    char: "頁",
    hanViet: "Bộ hiệt",
    meaningVi: "Đầu, trang sách, cái cổ con người.",
    meaningEn: "Page / Head",
    strokes: 9,
    strokeGuide: "Khung ngang trên, ở giữa là bộ tự (mắt), dưới là hai nét chân.",
    strokePaths: [
      "M 20 20 L 80 20",
      "M 32 32 L 32 68",
      "M 32 32 L 68 32 L 68 68",
      "M 32 44 L 68 44",
      "M 32 56 L 68 56",
      "M 32 68 L 68 68",
      "M 50 20 L 50 32",
      "M 40 75 C 32 82, 24 86, 16 88",
      "M 60 75 C 68 82, 76 86, 84 88",
    ],
    exampleKanji: [
      { char: "頁", pinyin: "yè", hanViet: "Hiệt", meaning: "Trang sách (ページ)" },
      { char: "頭", pinyin: "tóu", hanViet: "Đầu", meaning: "Cái đầu (頭)" },
    ],
  },

  // --- BẢNG BỔ SUNG 2 ---
  {
    id: "rad-dac",
    char: "弋",
    hanViet: "Bộ dặc",
    meaningVi: "Bắn tên có buộc dây, cọc gỗ đóng đất, dây buộc tên.",
    meaningEn: "Arrow with string / Stake",
    strokes: 3,
    strokeGuide: "Nét 1: ngang; Nét 2: nghiêng móc dài; Nét 3: chấm trên.",
    strokePaths: ["M 25 35 L 75 35", "M 48 18 L 65 85 C 68 88, 75 88, 80 82", "M 68 22 C 72 26, 75 30, 78 35"],
    exampleKanji: [
      { char: "式", pinyin: "shì", hanViet: "Thức", meaning: "Hình thức, lễ nghi" },
      { char: "弐", pinyin: "èr", hanViet: "Nhị", meaning: "Số 2 (dùng trong ngân hàng)" },
    ],
  },
  {
    id: "rad-qua",
    char: "戈",
    hanViet: "Bộ qua",
    meaningVi: "Binh khí chiến đấu, cây mâu, thương dài.",
    meaningEn: "Halberd / Dagger-axe",
    strokes: 4,
    strokeGuide: "Nét 1: ngang dài; Nét 2: nghiêng móc dài; Nét 3: phẩy ngắn; Nét 4: chấm trên.",
    strokePaths: ["M 20 38 L 80 38", "M 48 18 L 65 88 C 68 90, 75 90, 80 82", "M 48 45 C 38 58, 28 72, 18 82", "M 68 22 C 72 26, 75 30, 78 35"],
    exampleKanji: [
      { char: "成", pinyin: "chéng", hanViet: "Thành", meaning: "Hoàn thành, trở thành" },
      { char: "戦", pinyin: "zhàn", hanViet: "Chiến", meaning: "Chiến đấu, chiến tranh" },
    ],
  },
  {
    id: "rad-thi-dung",
    char: "礻",
    hanViet: "Bộ thị (thị đứng)",
    meaningVi: "Thần linh, cúng tế, tổ tiên, sự chỉ bảo (đứng bên trái).",
    meaningEn: "Altar / Spirits (standing)",
    strokes: 4,
    strokeGuide: "Nét 1: chấm; Nét 2: ngang gập phẩy; Nét 3: sổ đứng; Nét 4: chấm phải.",
    strokePaths: ["M 32 18 C 36 22, 38 26, 40 30", "M 22 38 L 52 38 L 28 65", "M 38 38 L 38 88", "M 48 60 C 52 65, 55 70, 58 75"],
    exampleKanji: [
      { char: "社", pinyin: "shè", hanViet: "Xã", meaning: "Công ty, xã hội (会社)" },
      { char: "神", pinyin: "shén", hanViet: "Thần", meaning: "Thần thần linh (神社)" },
    ],
  },
  {
    id: "rad-y-dung",
    char: "衤",
    hanViet: "Bộ y (y đứng)",
    meaningVi: "Áo quần, trang phục, y phục con người (đứng bên trái).",
    meaningEn: "Clothes / Garment (standing)",
    strokes: 5,
    strokeGuide: "Khá giống bộ thị nhưng có thêm 1 nét hất/chấm ở dưới.",
    strokePaths: [
      "M 32 16 C 36 20, 38 24, 40 28",
      "M 22 35 L 52 35 L 28 60",
      "M 38 35 L 38 88",
      "M 45 52 C 50 56, 54 60, 58 64",
      "M 48 68 C 53 73, 58 78, 62 82",
    ],
    exampleKanji: [
      { char: "初", pinyin: "chū", hanViet: "Sơ", meaning: "Ban đầu, lần đầu (初めて)" },
      { char: "袋", pinyin: "dài", hanViet: "Đại", meaning: "Cái túi, bao tải" },
    ],
  },
  {
    id: "rad-dan",
    char: "廴",
    hanViet: "Bộ dẫn",
    meaningVi: "Bước chân dài, đi xa, kéo dài.",
    meaningEn: "Long stride / Move",
    strokes: 2,
    strokeGuide: "Nét 1: ngang gập phẩy; Nét 2: mác dẹp dài ôm chân.",
    strokePaths: ["M 30 25 L 60 25 L 35 50", "M 22 45 C 32 45, 45 62, 85 85"],
    exampleKanji: [
      { char: "延", pinyin: "yán", hanViet: "Diên", meaning: "Kéo dài, hoãn lại" },
      { char: "建", pinyin: "jiàn", hanViet: "Kiến", meaning: "Xây dựng (建物)" },
    ],
  },
  {
    id: "rad-suoc",
    char: "辶",
    hanViet: "Bộ sước",
    meaningVi: "Chợt đi chợt dừng, đường xá, hành trình di chuyển (nằm chân chữ).",
    meaningEn: "Walk / Movement (road)",
    strokes: 3,
    strokeGuide: "Nét 1: chấm trên; Nét 2: dẹp ngoằn ngoèo; Nét 3: mác dài kéo ôm dưới.",
    strokePaths: ["M 32 20 C 36 24, 38 28, 40 32", "M 22 42 L 48 42 L 28 62 L 45 66", "M 18 62 C 28 62, 45 78, 88 88"],
    exampleKanji: [
      { char: "道", pinyin: "dào", hanViet: "Đạo", meaning: "Con đường (道)" },
      { char: "送", pinyin: "sòng", hanViet: "Tống", meaning: "Gửi đi (送ります)" },
    ],
  },
  {
    id: "rad-thi-thay",
    char: "尸",
    hanViet: "Bộ thi",
    meaningVi: "Thây ma, xác chết, tư thế ngồi nghỉ.",
    meaningEn: "Corpse / Sitting body",
    strokes: 3,
    strokeGuide: "Nét 1: ngang gập; Nét 2: ngang; Nét 3: phẩy đứng dài bên trái.",
    strokePaths: ["M 25 25 L 75 25 L 75 52", "M 25 52 L 75 52", "M 25 25 C 23 50, 18 72, 12 88"],
    exampleKanji: [
      { char: "屋", pinyin: "wū", hanViet: "Ốc", meaning: "Căn nhà, cửa hàng (部屋)" },
      { char: "局", pinyin: "jú", hanViet: "Cục", meaning: "Cơ quan, cục (郵便局)" },
    ],
  },
  {
    id: "rad-ho-cua",
    char: "戸",
    hanViet: "Bộ hộ",
    meaningVi: "Cánh cửa 1 cánh, nhà cửa, hộ gia đình.",
    meaningEn: "Door / Household",
    strokes: 4,
    strokeGuide: "Nét 1: ngang đỉnh; Nét 2: ngang gập; Nét 3: ngang giữa; Nét 4: phẩy trái.",
    strokePaths: ["M 20 22 L 78 22", "M 32 38 L 78 38 L 78 60", "M 32 60 L 78 60", "M 32 38 C 30 58, 22 76, 12 88"],
    exampleKanji: [
      { char: "戸", pinyin: "hù", hanViet: "Hộ", meaning: "Cánh cửa (神戸 - Kobe)" },
      { char: "所", pinyin: "suǒ", hanViet: "Sở", meaning: "Nơi chốn (所)" },
    ],
  },
  {
    id: "rad-tich",
    char: "夕",
    hanViet: "Bộ tịch",
    meaningVi: "Buổi chiều tà, hoàng hôn, đêm tối.",
    meaningEn: "Evening / Sunset",
    strokes: 3,
    strokeGuide: "Nét 1: phẩy nghiêng trái; Nét 2: ngang gập phẩy; Nét 3: chấm giữa.",
    strokePaths: ["M 52 18 C 42 32, 32 45, 22 55", "M 28 38 L 78 38 L 38 88", "M 42 55 C 50 62, 58 68, 65 72"],
    exampleKanji: [
      { char: "夕", pinyin: "xī", hanViet: "Tịch", meaning: "Chiều tối (夕方)" },
      { char: "多", pinyin: "duō", hanViet: "Đa", meaning: "Nhiều (多い)" },
    ],
  },
  {
    id: "rad-dai",
    char: "歹",
    hanViet: "Bộ đãi (ngạt)",
    meaningVi: "Xương tàn, chết chóc, xui xẻo tàn rụi.",
    meaningEn: "Death / Decay",
    strokes: 4,
    strokeGuide: "Nét 1: ngang trên; Nét 2: phẩy gập; Nét 3: phẩy trái; Nét 4: mác phải.",
    strokePaths: ["M 25 25 L 75 25", "M 52 25 L 28 48 L 48 55", "M 48 55 C 38 68, 28 78, 15 88", "M 48 55 C 58 68, 72 78, 85 88"],
    exampleKanji: [
      { char: "死", pinyin: "sǐ", hanViet: "Tử", meaning: "Chết (死にます)" },
      { char: "残", pinyin: "cán", hanViet: "Tàn", meaning: "Còn lại, tàn dư" },
    ],
  },
  {
    id: "rad-nhat",
    char: "日",
    hanViet: "Bộ nhật",
    meaningVi: "Mặt trời, ban ngày, thời gian, Nhật Bản.",
    meaningEn: "Sun / Day",
    strokes: 4,
    strokeGuide: "Nét 1: sổ trái; Nét 2: ngang gập; Nét 3: ngang giữa; Nét 4: ngang đáy.",
    strokePaths: ["M 25 20 L 25 82", "M 25 20 L 75 20 L 75 82", "M 25 50 L 75 50", "M 25 82 L 75 82"],
    exampleKanji: [
      { char: "日", pinyin: "rì", hanViet: "Nhật", meaning: "Mặt trời, ngày (日本)" },
      { char: "明", pinyin: "míng", hanViet: "Minh", meaning: "Sáng sủa (明るい)" },
    ],
  },
  {
    id: "rad-viet",
    char: "曰",
    hanViet: "Bộ viết",
    meaningVi: "Nói rằng, rằng là (hình dáng rộng bẹt hơn bộ nhật).",
    meaningEn: "Say / Speak",
    strokes: 4,
    strokeGuide: "Giống bộ nhật nhưng hình dáng rộng bẹt chiều ngang hơn.",
    strokePaths: ["M 18 28 L 18 78", "M 18 28 L 82 28 L 82 78", "M 18 52 L 82 52", "M 18 78 L 82 78"],
    exampleKanji: [
      { char: "書", pinyin: "shū", hanViet: "Thư", meaning: "Viết, cuốn sách (書きます)" },
      { char: "最", pinyin: "zuì", hanViet: "Tối", meaning: "Nhất, tối đa (最近)" },
    ],
  },
  {
    id: "rad-can-khan",
    char: "巾",
    hanViet: "Bộ cân (khăn)",
    meaningVi: "Khăn tay, dải vải, lá cờ.",
    meaningEn: "Towel / Cloth",
    strokes: 3,
    strokeGuide: "Nét 1: sổ trái; Nét 2: ngang gập; Nét 3: sổ dài chính giữa.",
    strokePaths: ["M 22 30 L 22 70", "M 22 30 L 78 30 L 78 70", "M 50 15 L 50 88"],
    exampleKanji: [
      { char: "市", pinyin: "shì", hanViet: "Thị", meaning: "Thành phố, chợ (市民)" },
      { char: "布", pinyin: "bù", hanViet: "Bố", meaning: "Vải vóc" },
    ],
  },
  {
    id: "rad-can-riu",
    char: "斤",
    hanViet: "Bộ cân (rìu)",
    meaningVi: "Cái rìu đốn gỗ, đơn vị đo khối lượng cân.",
    meaningEn: "Axe / Weight unit",
    strokes: 4,
    strokeGuide: "Nét 1: phẩy nằm; Nét 2: phẩy đứng; Nét 3: ngang; Nét 4: sổ đứng.",
    strokePaths: ["M 65 18 C 50 25, 38 32, 28 38", "M 32 38 C 28 55, 20 74, 12 88", "M 32 48 L 80 48", "M 62 48 L 62 88"],
    exampleKanji: [
      { char: "新", pinyin: "xīn", hanViet: "Tân", meaning: "Mới mẻ (新しい)" },
      { char: "所", pinyin: "suǒ", hanViet: "Sở", meaning: "Nơi chốn" },
    ],
  },

  // --- BẢNG BỔ SUNG 2 - HÀNG 2 ---
  {
    id: "rad-thao",
    char: "艹",
    hanViet: "Bộ thảo",
    meaningVi: "Cỏ cây, hoa lá, thảo mộc thiên nhiên (nằm ở đỉnh chữ).",
    meaningEn: "Grass / Vegetation",
    strokes: 3,
    strokeGuide: "Nét 1: ngang dài; Nét 2: sổ ngắn trái; Nét 3: sổ ngắn phải.",
    strokePaths: ["M 18 35 L 82 35", "M 38 20 L 38 50", "M 62 20 L 62 50"],
    exampleKanji: [
      { char: "花", pinyin: "huā", hanViet: "Hoa", meaning: "Bông hoa (花)" },
      { char: "茶", pinyin: "chá", hanViet: "Trà", meaning: "Nước trà (お茶)" },
    ],
  },
  {
    id: "rad-thi-ten",
    char: "矢",
    hanViet: "Bộ thỉ (mũi tên)",
    meaningVi: "Mũi tên, bắn tên, sự thẳng thắn.",
    meaningEn: "Arrow",
    strokes: 5,
    strokeGuide: "Nét 1: phẩy nằm; Nét 2: ngang ngắn; Nét 3: ngang dài; Nét 4: phẩy trái; Nét 5: mác phải.",
    strokePaths: ["M 55 15 C 42 22, 32 26, 25 28", "M 28 35 L 72 35", "M 18 52 L 82 52", "M 50 35 C 40 55, 28 72, 14 86", "M 50 52 C 60 65, 72 78, 85 86"],
    exampleKanji: [
      { char: "知", pinyin: "zhī", hanViet: "Tri", meaning: "Biết, tri thức (知ります)" },
      { char: "短", pinyin: "duǎn", hanViet: "Đoản", meaning: "Ngắn" },
    ],
  },
  {
    id: "rad-thi-heo",
    char: "豕",
    hanViet: "Bộ thỉ (heo)",
    meaningVi: "Con heo, con lợn gia súc.",
    meaningEn: "Pig / Swine",
    strokes: 7,
    strokeGuide: "Nét 1: ngang; Nét 2: phẩy móc giữa; Nét 3-7: các nét cong chân lợn.",
    strokePaths: [
      "M 25 22 L 75 22",
      "M 48 22 C 38 42, 28 65, 18 85",
      "M 45 35 L 68 45",
      "M 42 50 C 35 60, 25 70, 15 78",
      "M 45 62 L 75 75",
      "M 45 70 L 82 88",
      "M 55 25 L 82 38",
    ],
    exampleKanji: [
      { char: "豚", pinyin: "tún", hanViet: "Đốn", meaning: "Thịt lợn (豚肉)" },
      { char: "象", pinyin: "xiàng", hanViet: "Tượng", meaning: "Con voi, hình tượng" },
    ],
  },
  {
    id: "rad-khiem",
    char: "欠",
    hanViet: "Bộ khiếm",
    meaningVi: "Há miệng ngáp, khiếm khuyết, thiếu hụt.",
    meaningEn: "Yawn / Lack",
    strokes: 4,
    strokeGuide: "Nét 1: phẩy ngắn; Nét 2: ngang gập; Nét 3: phẩy trái; Nét 4: mác phải.",
    strokePaths: ["M 55 18 C 45 25, 38 30, 30 35", "M 32 35 L 75 35 L 48 55", "M 48 55 C 38 68, 28 80, 15 88", "M 48 55 C 58 68, 72 80, 85 88"],
    exampleKanji: [
      { char: "歌", pinyin: "gē", hanViet: "Ca", meaning: "Bài hát, ca hát (歌)" },
      { char: "飲", pinyin: "yǐn", hanViet: "Ẩm", meaning: "Uống (飲みます)" },
    ],
  },
  {
    id: "rad-thu-gai",
    char: "殳",
    hanViet: "Bộ thù",
    meaningVi: "Gậy binh khí gỗ, binh khí rèn đúc.",
    meaningEn: "Weapon / Strike",
    strokes: 4,
    strokeGuide: "Nét 1: phẩy gập ngang; Nét 2: ngang gập; Nét 3: phẩy; Nét 4: mác.",
    strokePaths: ["M 25 22 L 55 22 L 40 40", "M 40 40 L 75 40 L 48 60", "M 48 60 C 38 72, 28 82, 15 88", "M 48 60 C 58 72, 72 82, 85 88"],
    exampleKanji: [
      { char: "段", pinyin: "duàn", hanViet: "Đoạn", meaning: "Giai đoạn, bậc thang" },
      { char: "役", pinyin: "yì", hanViet: "Dịch", meaning: "Vai trò, phục vụ" },
    ],
  },
  {
    id: "rad-chuy",
    char: "匕",
    hanViet: "Bộ chủy",
    meaningVi: "Cái thìa múc cơm, con dao nhỏ gọt hoa quả.",
    meaningEn: "Spoon / Dagger",
    strokes: 2,
    strokeGuide: "Nét 1: phẩy nằm trái; Nét 2: sổ gập móc hất lên.",
    strokePaths: ["M 68 25 C 52 32, 38 40, 25 45", "M 38 18 L 38 68 C 38 82, 60 85, 78 78"],
    exampleKanji: [
      { char: "北", pinyin: "běi", hanViet: "Bắc", meaning: "Phía bắc (北)" },
      { char: "匙", pinyin: "chí", hanViet: "Thìa", meaning: "Cái thìa" },
    ],
  },
  {
    id: "rad-cung",
    char: "弓",
    hanViet: "Bộ cung",
    meaningVi: "Cây cung bắn tên, uốn cong uốn lượn.",
    meaningEn: "Bow",
    strokes: 3,
    strokeGuide: "Nét 1: ngang gập; Nét 2: ngang; Nét 3: sổ gập cong móc.",
    strokePaths: ["M 25 25 L 75 25 L 45 45", "M 45 45 L 70 45", "M 70 45 L 35 60 C 35 75, 78 78, 75 88"],
    exampleKanji: [
      { char: "強", pinyin: "qiáng", hanViet: "Cường", meaning: "Mạnh mẽ (勉強します)" },
      { char: "引", pinyin: "yǐn", hanViet: "Dẫn", meaning: "Kéo" },
    ],
  },
  {
    id: "rad-bao",
    char: "勹",
    hanViet: "Bộ bao",
    meaningVi: "Bao bọc, gói lại, ôm lấy che chở.",
    meaningEn: "Wrap / Package",
    strokes: 2,
    strokeGuide: "Nét 1: phẩy nghiêng trái; Nét 2: ngang gập móc bao bọc.",
    strokePaths: ["M 55 18 C 42 28, 32 38, 22 45", "M 32 32 L 80 32 L 60 88 C 55 92, 45 92, 38 85"],
    exampleKanji: [
      { char: "包", pinyin: "bāo", hanViet: "Bao", meaning: "Gói lại, bao bọc" },
      { char: "句", pinyin: "jù", hanViet: "Cú", meaning: "Câu văn (文句)" },
    ],
  },
  {
    id: "rad-chuoc",
    char: "勺",
    hanViet: "Bộ chước",
    meaningVi: "Cái muôi, cái thìa múc rượu, đong lường thể tích.",
    meaningEn: "Ladle / Spoon / Unit of volume",
    strokes: 2,
    strokeGuide: "Nét 1: phẩy trái nghiêng; Nét 2: ngang gập móc bao ngoài và nét chấm bên trong.",
    strokePaths: ["M 38 18 C 30 35, 22 55, 12 78", "M 32 30 L 78 30 L 68 85 C 62 92, 50 92, 42 85", "M 48 52 C 52 52, 55 55, 55 58 C 55 62, 52 65, 48 65 C 44 65, 41 62, 41 58 C 41 55, 44 52, 48 52"],
    exampleKanji: [
      { char: "約", pinyin: "yuē", hanViet: "Ước", meaning: "Giao ước, khoảng (約束)" },
      { char: "酌", pinyin: "zhuó", hanViet: "Chước", meaning: "Rót rượu, chuốc rượu" },
    ],
  },

  // --- BẢNG BỔ SUNG 2 - HÀNG 3 ---
  {
    id: "rad-vong",
    char: "罒",
    hanViet: "Bộ võng",
    meaningVi: "Cái lưới đánh cá, cái bẫy trùm lên đỉnh.",
    meaningEn: "Net",
    strokes: 5,
    strokeGuide: "Khung hình chữ nhật bẹt có 2 nét sổ ngắn bên trong.",
    strokePaths: ["M 18 35 L 18 65", "M 18 35 L 82 35 L 82 65", "M 38 35 L 38 65", "M 62 35 L 62 65", "M 18 65 L 82 65"],
    exampleKanji: [
      { char: "署", pinyin: "shǔ", hanViet: "Thự", meaning: "Ký tên, cơ quan" },
      { char: "罪", pinyin: "zuì", hanViet: "Tội", meaning: "Tội lỗi, tội phạm" },
    ],
  },
  {
    id: "rad-manh",
    char: "皿",
    hanViet: "Bộ mãnh",
    meaningVi: "Bát đĩa, đồ đĩa bẹt đựng thức ăn.",
    meaningEn: "Dish / Plate",
    strokes: 5,
    strokeGuide: "Khung đáy hình bát đĩa bẹt nằm ở chân chữ.",
    strokePaths: ["M 22 45 L 22 78", "M 22 45 L 78 45 L 78 78", "M 40 45 L 40 78", "M 60 45 L 60 78", "M 15 78 L 85 78"],
    exampleKanji: [
      { char: "皿", pinyin: "mǐn", hanViet: "Mãnh", meaning: "Cái đĩa" },
      { char: "盛", pinyin: "shèng", hanViet: "Thịnh", meaning: "Sầm uất, thịnh vượng" },
    ],
  },
  {
    id: "rad-tay",
    char: "覀",
    hanViet: "Bộ tây",
    meaningVi: "Phương tây, nắp úp che đậy.",
    meaningEn: "West / Cover",
    strokes: 6,
    strokeGuide: "Khung nắp úp ở đỉnh chữ.",
    strokePaths: ["M 20 20 L 80 20", "M 28 32 L 28 68", "M 28 32 L 72 32 L 72 68", "M 42 32 L 42 68", "M 58 32 L 58 68", "M 28 68 L 72 68"],
    exampleKanji: [
      { char: "要", pinyin: "yào", hanViet: "Yếu", meaning: "Cần thiết (必要)" },
      { char: "栗", pinyin: "lì", hanViet: "Lật", meaning: "Hạt dẻ" },
    ],
  },
  {
    id: "rad-dau-ruou",
    char: "酉",
    hanViet: "Bộ dậu",
    meaningVi: "Vò rượu, đồ lên men, địa chi giờ Dậu.",
    meaningEn: "Wine vessel / Liquor",
    strokes: 7,
    strokeGuide: "Nét 1: ngang đỉnh; Nét 2: sổ trái; Nét 3: ngang gập; Nét 4-6: ruột bên trong; Nét 7: ngang đáy.",
    strokePaths: [
      "M 22 20 L 78 20",
      "M 28 32 L 28 78",
      "M 28 32 L 72 32 L 72 78",
      "M 42 32 L 42 58",
      "M 58 32 L 58 58",
      "M 28 58 L 72 58",
      "M 28 78 L 72 78",
    ],
    exampleKanji: [
      { char: "酒", pinyin: "jiǔ", hanViet: "Tửu", meaning: "Rượu (お酒)" },
      { char: "配", pinyin: "pèi", hanViet: "Phối", meaning: "Phân phối, lo lắng (心配)" },
    ],
  },
  {
    id: "rad-truy-chim",
    char: "隹",
    hanViet: "Bộ truy (chim đuôi ngắn)",
    meaningVi: "Con chim đuôi ngắn, các loài chim nhỏ.",
    meaningEn: "Short-tailed bird",
    strokes: 8,
    strokeGuide: "Cụm đầu chim phẩy trên, thân hình chữ nhật nhiều nét ngang.",
    strokePaths: [
      "M 38 15 C 30 22, 22 28, 15 32",
      "M 30 30 L 30 85",
      "M 48 20 L 48 35",
      "M 48 35 L 85 35",
      "M 48 50 L 85 50",
      "M 48 65 L 85 65",
      "M 48 85 L 85 85",
      "M 65 35 L 65 85",
    ],
    exampleKanji: [
      { char: "難", pinyin: "nán", hanViet: "Nan", meaning: "Khó khăn (難しい)" },
      { char: "集", pinyin: "jí", hanViet: "Tập", meaning: "Tập hợp, thu thập" },
    ],
  },
  {
    id: "rad-at",
    char: "乙",
    hanViet: "Bộ ất",
    meaningVi: "Vị trí thứ 2 trong Thiên Can, nét lằn ngoằn cong queo.",
    meaningEn: "Second / Twist",
    strokes: 1,
    strokeGuide: "Kéo nét ngang gập cong hất móc nhẹ.",
    strokePaths: ["M 25 30 L 70 30 L 45 55 C 45 75, 78 78, 80 88"],
    exampleKanji: [
      { char: "乙", pinyin: "yǐ", hanViet: "Ất", meaning: "Thứ hai, can Ất" },
      { char: "九", pinyin: "jiǔ", hanViet: "Cửu", meaning: "Số 9 (九)" },
    ],
  },
  {
    id: "rad-an",
    char: "乚",
    hanViet: "Bộ ẩn",
    meaningVi: "Nét hất móc rãnh sâu, sự ẩn giấu.",
    meaningEn: "Hidden / Hook",
    strokes: 1,
    strokeGuide: "Nét sổ kéo dài xuống rồi uốn cong móc hất lên phải.",
    strokePaths: ["M 35 20 L 35 70 C 35 85, 65 85, 82 78"],
    exampleKanji: [
      { char: "乱", pinyin: "luàn", hanViet: "Loạn", meaning: "Hỗn loạn, lộn xộn" },
      { char: "乳", pinyin: "rǔ", hanViet: "Nhũ", meaning: "Sữa (牛乳)" },
    ],
  },

  // --- BẢNG BỔ SUNG 2 - HÀNG 4 ---
  {
    id: "rad-kham",
    char: "凵",
    hanViet: "Bộ khảm",
    meaningVi: "Há miệng, cái hố sập há ra hướng lên.",
    meaningEn: "Open box / Pit",
    strokes: 2,
    strokeGuide: "Khung hình chữ U ngửa miệng lên trên.",
    strokePaths: ["M 25 25 L 25 75 L 75 75", "M 75 25 L 75 75"],
    exampleKanji: [
      { char: "出", pinyin: "chū", hanViet: "Xuất", meaning: "Ra ngoài" },
      { char: "函", pinyin: "hán", hanViet: "Hàm", meaning: "Hòm, thư từ" },
    ],
  },
  {
    id: "rad-ky-ban",
    char: "几",
    hanViet: "Bộ kỷ (bàn)",
    meaningVi: "Ghế tựa, cái bàn nhỏ uống trà.",
    meaningEn: "Table / Stool",
    strokes: 2,
    strokeGuide: "Nét 1: phẩy trái; Nét 2: ngang gập móc phải.",
    strokePaths: ["M 30 25 C 28 48, 22 70, 15 85", "M 30 25 L 75 25 L 75 75 C 75 85, 80 88, 85 85"],
    exampleKanji: [
      { char: "机", pinyin: "jī", hanViet: "Kỷ", meaning: "Cái bàn học (机)" },
      { char: "風", pinyin: "fēng", hanViet: "Phong", meaning: "Gió (風)" },
    ],
  },
  {
    id: "rad-cung-tay",
    char: "廾",
    hanViet: "Bộ củng",
    meaningVi: "Hai tay chắp lại nâng đón đồ vật.",
    meaningEn: "Two hands / Hold",
    strokes: 3,
    strokeGuide: "Nét 1: ngang dài; Nét 2: phẩy trái; Nét 3: sổ thẳng phải.",
    strokePaths: ["M 18 35 L 82 35", "M 38 20 C 35 45, 28 68, 18 85", "M 62 20 L 62 85"],
    exampleKanji: [
      { char: "弁", pinyin: "biàn", hanViet: "Biện", meaning: "Biện luận, cơm hộp (弁当)" },
      { char: "弊", pinyin: "bì", hanViet: "Tệ", meaning: "Tệ hại, nhún nhường" },
    ],
  },
  {
    id: "rad-can-cung",
    char: "艮",
    hanViet: "Bộ cấn",
    meaningVi: "Dừng lại, quẻ Cấn (núi), sự cứng cỏi bền bỉ.",
    meaningEn: "Stopping / Tough",
    strokes: 6,
    strokeGuide: "Nét 1: ngang gập; Nét 2: ngang; Nét 3: ngang; Nét 4: phẩy; Nét 5: mác.",
    strokePaths: ["M 32 18 L 72 18 L 72 45 L 32 45", "M 32 32 L 72 32", "M 32 45 L 32 88", "M 32 58 C 42 68, 55 78, 75 85"],
    exampleKanji: [
      { char: "良", pinyin: "liáng", hanViet: "Lương", meaning: "Tốt lành (良い)" },
      { char: "退", pinyin: "tuì", hanViet: "Thoái", meaning: "Rút lui, nghỉ hưu" },
    ],
  },
  {
    id: "rad-duat",
    char: "聿",
    hanViet: "Bộ duật",
    meaningVi: "Cây bút viết chữ, công việc sáng tác.",
    meaningEn: "Brush / Writing instrument",
    strokes: 6,
    strokeGuide: "Các nét ngang song song và 1 nét sổ đứng xuyên qua giữa.",
    strokePaths: [
      "M 25 22 L 75 22",
      "M 20 38 L 80 38",
      "M 25 54 L 75 54",
      "M 20 70 L 80 70",
      "M 50 12 L 50 88",
    ],
    exampleKanji: [
      { char: "書", pinyin: "shū", hanViet: "Thư", meaning: "Viết, cuốn sách (書きます)" },
      { char: "津", pinyin: "jīn", hanViet: "Tân", meaning: "Bến sông" },
    ],
  },
  {
    id: "rad-lap",
    char: "立",
    hanViet: "Bộ lập",
    meaningVi: "Đứng thẳng trên mặt đất, thành lập, thiết lập.",
    meaningEn: "Stand",
    strokes: 5,
    strokeGuide: "Nét 1: chấm đỉnh; Nét 2: ngang ngắn; Nét 3: phẩy trái; Nét 4: chấm phải; Nét 5: ngang đáy dài.",
    strokePaths: ["M 50 15 L 50 28", "M 25 28 L 75 28", "M 38 42 L 30 62", "M 62 42 L 70 62", "M 15 78 L 85 78"],
    exampleKanji: [
      { char: "立", pinyin: "lì", hanViet: "Lập", meaning: "Đứng lên (立ちます)" },
      { char: "音", pinyin: "yīn", hanViet: "Âm", meaning: "Âm thanh (音楽)" },
    ],
  },
  {
    id: "rad-trung",
    char: "虫",
    hanViet: "Bộ trùng",
    meaningVi: "Côn trùng, sâu bọ, động vật thân mềm.",
    meaningEn: "Insect / Worm",
    strokes: 6,
    strokeGuide: "Nét 1: ô khẩu trên; Nét 2: sổ đứng xuyên giữa; Nét 3: hất dưới; Nét 4: chấm phải.",
    strokePaths: [
      "M 28 20 L 28 50",
      "M 28 20 L 72 20 L 72 50",
      "M 28 50 L 72 50",
      "M 50 12 L 50 82",
      "M 22 82 L 50 82",
      "M 65 65 C 72 72, 78 78, 82 82",
    ],
    exampleKanji: [
      { char: "虫", pinyin: "chóng", hanViet: "Trùng", meaning: "Côn trùng, sâu" },
      { char: "強", pinyin: "qiáng", hanViet: "Cường", meaning: "Mạnh mẽ (勉強)" },
    ],
  },
  {
    id: "rad-ngon",
    char: "言",
    hanViet: "Bộ ngôn",
    meaningVi: "Lời nói, ngôn ngữ, phát ngôn con người.",
    meaningEn: "Speech / Words",
    strokes: 7,
    strokeGuide: "Nét 1: chấm; Nét 2-4: 3 nét ngang; Nét 5-7: bộ khẩu bên dưới.",
    strokePaths: [
      "M 50 12 L 50 20",
      "M 20 24 L 80 24",
      "M 32 36 L 68 36",
      "M 32 46 L 68 46",
      "M 32 58 L 32 82",
      "M 32 58 L 68 58 L 68 82",
      "M 32 82 L 68 82",
    ],
    exampleKanji: [
      { char: "言", pinyin: "yán", hanViet: "Ngôn", meaning: "Nói (言います)" },
      { char: "語", pinyin: "yǔ", hanViet: "Ngữ", meaning: "Ngôn ngữ (日本語)" },
    ],
  },
  {
    id: "rad-dau-hat",
    char: "豆",
    hanViet: "Bộ đậu",
    meaningVi: "Hạt đậu, mâm cúng cổ đựng đồ tế lễ.",
    meaningEn: "Bean / Vessel",
    strokes: 7,
    strokeGuide: "Nét 1: ngang; Nét 2-4: ô khẩu; Nét 5-6: hai phẩy chân; Nét 7: ngang đáy.",
    strokePaths: [
      "M 22 18 L 78 18",
      "M 30 30 L 30 52",
      "M 30 30 L 70 30 L 70 52",
      "M 30 52 L 70 52",
      "M 38 62 L 28 78",
      "M 62 62 L 72 78",
      "M 15 88 L 85 88",
    ],
    exampleKanji: [
      { char: "豆", pinyin: "dòu", hanViet: "Đậu", meaning: "Hạt đậu (豆腐)" },
      { char: "頭", pinyin: "tóu", hanViet: "Đầu", meaning: "Cái đầu (頭)" },
    ],
  },
  {
    id: "rad-coc",
    char: "谷",
    hanViet: "Bộ cốc",
    meaningVi: "Hang núi, thung lũng khe suối.",
    meaningEn: "Valley",
    strokes: 7,
    strokeGuide: "Nét 1-2: phẩy mác trên; Nét 3-4: nhân trên; Nét 5-7: ô khẩu dưới.",
    strokePaths: [
      "M 35 15 L 22 28",
      "M 65 15 L 78 28",
      "M 50 28 L 25 50",
      "M 50 28 L 75 50",
      "M 32 60 L 32 85",
      "M 32 60 L 68 60 L 68 85",
      "M 32 85 L 68 85",
    ],
    exampleKanji: [
      { char: "谷", pinyin: "gǔ", hanViet: "Cốc", meaning: "Thung lũng (谷)" },
      { char: "容", pinyin: "róng", hanViet: "Dung", meaning: "Nội dung, dung mạo" },
    ],
  },
  {
    id: "rad-boi",
    char: "卜",
    hanViet: "Bộ bói",
    meaningVi: "Bói toán, hình vết nứt nổ rạn trên mu rùa.",
    meaningEn: "Divination / Fortune",
    strokes: 2,
    strokeGuide: "Nét 1: sổ đứng; Nét 2: chấm/ngang hất phải.",
    strokePaths: ["M 45 15 L 45 88", "M 45 42 L 78 42"],
    exampleKanji: [
      { char: "卜", pinyin: "bǔ", hanViet: "Bói", meaning: "Bói toán" },
      { char: "外", pinyin: "wài", hanViet: "Ngoại", meaning: "Bên ngoài (外国)" },
    ],
  },
  {
    id: "rad-xuyen",
    char: "巛",
    hanViet: "Bộ xuyên",
    meaningVi: "Dòng sông, con suối, nước chảy cuồn cuộn.",
    meaningEn: "River / Stream",
    strokes: 3,
    strokeGuide: "3 nét lằn sóng ngoằn ngoèo chảy song song từ trên xuống.",
    strokePaths: ["M 28 20 L 22 50 L 28 85", "M 50 20 L 44 50 L 50 85", "M 72 20 L 66 50 L 72 85"],
    exampleKanji: [
      { char: "川", pinyin: "chuān", hanViet: "Xuyên", meaning: "Dòng sông (川)" },
      { char: "州", pinyin: "zhōu", hanViet: "Châu", meaning: "Tỉnh, tiểu bang" },
    ],
  },
];

export function getRadicalById(id: string): KanjiRadical | undefined {
  return KANJI_RADICALS.find((r) => r.id === id);
}
