import { Script } from "./kana";

export type PhraseFormality = "polite" | "casual" | "formal";

export type PhraseTheme =
  | "all"
  | "greetings"
  | "travel"
  | "dining_shopping"
  | "school_study"
  | "work_business"
  | "emergency";

export type PhraseTopic =
  | "all"
  | "greetings_basic"
  | "introductions"
  | "gratitude_apology"
  | "asking_directions"
  | "transportation"
  | "restaurant_dining"
  | "shopping_prices"
  | "classroom_study"
  | "asking_questions"
  | "workplace_office"
  | "health_emergency";

export interface Phrase {
  id: string;
  japanese: string;
  hiragana: string;
  romaji: string;
  english: string;
  vietnamese: string;
  theme: PhraseTheme;
  topic: PhraseTopic;
  formality: PhraseFormality;
  notesEn?: string;
  notesVi?: string;
}

export const PHRASE_THEMES: { id: PhraseTheme; labelEn: string; labelVi: string }[] = [
  { id: "all", labelEn: "All Themes", labelVi: "Tất cả chủ đề" },
  { id: "greetings", labelEn: "Greetings & Basics", labelVi: "Chào hỏi & Cơ bản" },
  { id: "travel", labelEn: "Travel & Directions", labelVi: "Du lịch & Hỏi đường" },
  { id: "dining_shopping", labelEn: "Dining & Shopping", labelVi: "Ăn uống & Mua sắm" },
  { id: "school_study", labelEn: "School & Study", labelVi: "Học tập & Trường học" },
  { id: "work_business", labelEn: "Work & Office", labelVi: "Công việc & Văn phòng" },
  { id: "emergency", labelEn: "Health & Emergency", labelVi: "Sức khỏe & Khẩn cấp" },
];

export const PHRASE_TOPICS: { id: PhraseTopic; theme: PhraseTheme; labelEn: string; labelVi: string }[] = [
  { id: "greetings_basic", theme: "greetings", labelEn: "Daily Greetings", labelVi: "Chào hỏi hàng ngày" },
  { id: "introductions", theme: "greetings", labelEn: "Self Introductions", labelVi: "Giới thiệu bản thân" },
  { id: "gratitude_apology", theme: "greetings", labelEn: "Thanks & Apologies", labelVi: "Cảm ơn & Xin lỗi" },
  { id: "asking_directions", theme: "travel", labelEn: "Asking Directions", labelVi: "Hỏi đường" },
  { id: "transportation", theme: "travel", labelEn: "Trains & Transport", labelVi: "Tàu xe & Di chuyển" },
  { id: "restaurant_dining", theme: "dining_shopping", labelEn: "Restaurant & Ordering", labelVi: "Nhà hàng & Gọi món" },
  { id: "shopping_prices", theme: "dining_shopping", labelEn: "Shopping & Prices", labelVi: "Mua sắm & Giá cả" },
  { id: "classroom_study", theme: "school_study", labelEn: "Classroom Expressions", labelVi: "Mẫu câu trong lớp học" },
  { id: "asking_questions", theme: "school_study", labelEn: "Asking Questions", labelVi: "Hỏi ý nghĩa & Cách nói" },
  { id: "workplace_office", theme: "work_business", labelEn: "Office Expressions", labelVi: "Giao tiếp văn phòng" },
  { id: "health_emergency", theme: "emergency", labelEn: "Medical & Emergencies", labelVi: "Y tế & Khẩn cấp" },
];

export const FORMALITY_LABELS: Record<PhraseFormality, { en: string; vi: string }> = {
  polite: { en: "Polite (丁寧語)", vi: "Lịch sự (丁寧語)" },
  casual: { en: "Casual (タメ口)", vi: "Thân mật (タメ口)" },
  formal: { en: "Formal / Keigo (敬語)", vi: "Trang trọng / Kính ngữ" },
};

export const PHRASE_LIST: Phrase[] = [
  // --- 1. GREETINGS & BASICS: Daily Greetings ---
  {
    id: "p-01",
    japanese: "おはようございます。",
    hiragana: "おはようございます。",
    romaji: "Ohayou gozaimasu.",
    english: "Good morning.",
    vietnamese: "Xin chào buổi sáng.",
    theme: "greetings",
    topic: "greetings_basic",
    formality: "polite",
    notesEn: "Used in the morning until around 10:00 AM.",
    notesVi: "Dùng vào buổi sáng cho đến khoảng 10 giờ sáng.",
  },
  {
    id: "p-02",
    japanese: "こんにちは。",
    hiragana: "こんにちは。",
    romaji: "Konnichiwa.",
    english: "Hello / Good afternoon.",
    vietnamese: "Xin chào (buổi trưa/chiều).",
    theme: "greetings",
    topic: "greetings_basic",
    formality: "polite",
    notesEn: "General daytime greeting.",
    notesVi: "Lời chào chung trong ngày.",
  },
  {
    id: "p-03",
    japanese: "こんばんは。",
    hiragana: "こんばんは。",
    romaji: "Konbanwa.",
    english: "Good evening.",
    vietnamese: "Xin chào buổi tối.",
    theme: "greetings",
    topic: "greetings_basic",
    formality: "polite",
    notesEn: "Used after sunset.",
    notesVi: "Dùng sau khi trời tối.",
  },
  {
    id: "p-04",
    japanese: "おやすみなさい。",
    hiragana: "おやすみなさい。",
    romaji: "Oyasumi nasai.",
    english: "Good night.",
    vietnamese: "Chúc ngủ ngon.",
    theme: "greetings",
    topic: "greetings_basic",
    formality: "polite",
    notesEn: "Said before going to bed or parting at night.",
    notesVi: "Nói trước khi đi ngủ hoặc chào tạm biệt vào buổi tối.",
  },
  {
    id: "p-05",
    japanese: "お元気ですか？",
    hiragana: "おげんきですか？",
    romaji: "O-genki desu ka?",
    english: "How are you?",
    vietnamese: "Bạn có khỏe không?",
    theme: "greetings",
    topic: "greetings_basic",
    formality: "polite",
  },
  {
    id: "p-06",
    japanese: "はい、元気です！",
    hiragana: "はい、げんきです！",
    romaji: "Hai, genki desu!",
    english: "Yes, I am fine!",
    vietnamese: "Vâng, tôi khỏe!",
    theme: "greetings",
    topic: "greetings_basic",
    formality: "polite",
  },
  {
    id: "p-07",
    japanese: "またね！",
    hiragana: "またね！",
    romaji: "Mata ne!",
    english: "See you later!",
    vietnamese: "Hẹn gặp lại nhé!",
    theme: "greetings",
    topic: "greetings_basic",
    formality: "casual",
    notesEn: "Casual parting with friends.",
    notesVi: "Chào tạm biệt thân mật với bạn bè.",
  },
  {
    id: "p-08",
    japanese: "行ってきます！",
    hiragana: "いってきます！",
    romaji: "Ittekimasu!",
    english: "I'm off / See you later!",
    vietnamese: "Tôi đi đây nha!",
    theme: "greetings",
    topic: "greetings_basic",
    formality: "casual",
    notesEn: "Said when leaving home or office.",
    notesVi: "Nói khi rời khỏi nhà hoặc văn phòng.",
  },
  {
    id: "p-09",
    japanese: "いってらっしゃい！",
    hiragana: "いってらっしゃい！",
    romaji: "Itterasshai!",
    english: "Take care / Have a good day!",
    vietnamese: "Đi cẩn thận nhé!",
    theme: "greetings",
    topic: "greetings_basic",
    formality: "casual",
    notesEn: "Response to Ittekimasu.",
    notesVi: "Lời đáp lại khi ai đó nói Ittekimasu.",
  },
  {
    id: "p-10",
    japanese: "ただいま！",
    hiragana: "ただいま！",
    romaji: "Tadaima!",
    english: "I'm home!",
    vietnamese: "Tôi về rồi đây!",
    theme: "greetings",
    topic: "greetings_basic",
    formality: "casual",
    notesEn: "Said when arriving back home.",
    notesVi: "Nói khi về đến nhà.",
  },
  {
    id: "p-11",
    japanese: "おかえりなさい！",
    hiragana: "おかえりなさい！",
    romaji: "Okaerinasai!",
    english: "Welcome home!",
    vietnamese: "Mừng bạn đã về!",
    theme: "greetings",
    topic: "greetings_basic",
    formality: "polite",
  },

  // --- 1. GREETINGS & BASICS: Self Introductions ---
  {
    id: "p-12",
    japanese: "初めまして。どうぞよろしくお願いします。",
    hiragana: "はじめまして。どうぞよろしくおねがいします。",
    romaji: "Hajimemashite. Douzo yoroshiku onegaishimasu.",
    english: "Nice to meet you. Pleased to work with you.",
    vietnamese: "Rất hân hạnh được gặp bạn. Mong nhận được sự giúp đỡ.",
    theme: "greetings",
    topic: "introductions",
    formality: "polite",
    notesEn: "Essential phrase when meeting someone for the first time.",
    notesVi: "Mẫu câu quan trọng khi làm quen lần đầu.",
  },
  {
    id: "p-13",
    japanese: "お名前は何ですか？",
    hiragana: "おなまえはなんですか？",
    romaji: "O-namae wa nan desu ka?",
    english: "What is your name?",
    vietnamese: "Tên bạn là gì?",
    theme: "greetings",
    topic: "introductions",
    formality: "polite",
  },
  {
    id: "p-14",
    japanese: "私の名前はソンです。",
    hiragana: "わたしのなまえはそんです。",
    romaji: "Watashi no namae wa Son desu.",
    english: "My name is Son.",
    vietnamese: "Tên tôi là Sơn.",
    theme: "greetings",
    topic: "introductions",
    formality: "polite",
  },
  {
    id: "p-15",
    japanese: "どこから来ましたか？",
    hiragana: "どこからきましたか？",
    romaji: "Doko kara kimashita ka?",
    english: "Where are you from?",
    vietnamese: "Bạn đến từ đâu?",
    theme: "greetings",
    topic: "introductions",
    formality: "polite",
  },
  {
    id: "p-16",
    japanese: "ベトナムから来ました。",
    hiragana: "べとなむからきました。",
    romaji: "Betonamu kara kimashita.",
    english: "I came from Vietnam.",
    vietnamese: "Tôi đến từ Việt Nam.",
    theme: "greetings",
    topic: "introductions",
    formality: "polite",
  },
  {
    id: "p-17",
    japanese: "何歳ですか？",
    hiragana: "なんさいですか？",
    romaji: "Nansai desu ka?",
    english: "How old are you?",
    vietnamese: "Bạn bao nhiêu tuổi?",
    theme: "greetings",
    topic: "introductions",
    formality: "polite",
  },
  {
    id: "p-18",
    japanese: "お仕事は何ですか？",
    hiragana: "おしごとはなんですか？",
    romaji: "O-shigoto wa nan desu ka?",
    english: "What is your job?",
    vietnamese: "Công việc của bạn là gì?",
    theme: "greetings",
    topic: "introductions",
    formality: "polite",
  },
  {
    id: "p-19",
    japanese: "私はエンジニアです。",
    hiragana: "わたしはえんじにあです。",
    romaji: "Watashi wa enjiniea desu.",
    english: "I am an engineer.",
    vietnamese: "Tôi là kỹ sư.",
    theme: "greetings",
    topic: "introductions",
    formality: "polite",
  },

  // --- 1. GREETINGS & BASICS: Thanks & Apologies ---
  {
    id: "p-20",
    japanese: "ありがとうございます。",
    hiragana: "ありがとうございます。",
    romaji: "Arigatou gozaimasu.",
    english: "Thank you very much.",
    vietnamese: "Cảm ơn bạn rất nhiều.",
    theme: "greetings",
    topic: "gratitude_apology",
    formality: "polite",
  },
  {
    id: "p-21",
    japanese: "どうもありがとうございます！",
    hiragana: "どうもありがとうございます！",
    romaji: "Doumo arigatou gozaimasu!",
    english: "Thank you so very much!",
    vietnamese: "Xin chân thành cảm ơn!",
    theme: "greetings",
    topic: "gratitude_apology",
    formality: "polite",
  },
  {
    id: "p-22",
    japanese: "すみません。",
    hiragana: "すみません。",
    romaji: "Sumimasen.",
    english: "Excuse me / I'm sorry / Thank you.",
    vietnamese: "Xin lỗi / Cho tôi hỏi / Cảm ơn.",
    theme: "greetings",
    topic: "gratitude_apology",
    formality: "polite",
    notesEn: "Multi-purpose phrase to apologize or catch someone's attention.",
    notesVi: "Mẫu câu đa năng để xin lỗi, gọi ai đó hoặc cảm ơn.",
  },
  {
    id: "p-23",
    japanese: "ごめんなさい。",
    hiragana: "ごめんなさい。",
    romaji: "Gomen nasai.",
    english: "I am sorry.",
    vietnamese: "Tôi xin lỗi.",
    theme: "greetings",
    topic: "gratitude_apology",
    formality: "polite",
  },
  {
    id: "p-24",
    japanese: "申し訳ありません。",
    hiragana: "もうしわけありません。",
    romaji: "Moushiwake arimasen.",
    english: "I sincerely apologize.",
    vietnamese: "Tôi thành thật xin lỗi.",
    theme: "greetings",
    topic: "gratitude_apology",
    formality: "formal",
    notesEn: "Formal business apology.",
    notesVi: "Lời xin lỗi trang trọng trong kinh doanh.",
  },
  {
    id: "p-25",
    japanese: "どういたしまして。",
    hiragana: "どういたしまして。",
    romaji: "Dou itashimashite.",
    english: "You're welcome.",
    vietnamese: "Không có gì đâu.",
    theme: "greetings",
    topic: "gratitude_apology",
    formality: "polite",
  },

  // --- 2. TRAVEL & DIRECTIONS: Asking Directions ---
  {
    id: "p-26",
    japanese: "すみません、〜はどこですか？",
    hiragana: "すみません、〜はどこですか？",
    romaji: "Sumimasen, ... wa doko desu ka?",
    english: "Excuse me, where is ...?",
    vietnamese: "Xin lỗi, ... ở đâu vậy?",
    theme: "travel",
    topic: "asking_directions",
    formality: "polite",
  },
  {
    id: "p-27",
    japanese: "トイレはどこですか？",
    hiragana: "といれはどこですか？",
    romaji: "Toire wa doko desu ka?",
    english: "Where is the restroom?",
    vietnamese: "Nhà vệ sinh ở đâu?",
    theme: "travel",
    topic: "asking_directions",
    formality: "polite",
  },
  {
    id: "p-28",
    japanese: "駅はどこですか？",
    hiragana: "えきはどこですか？",
    romaji: "Eki wa doko desu ka?",
    english: "Where is the train station?",
    vietnamese: "Ga tàu ở đâu?",
    theme: "travel",
    topic: "asking_directions",
    formality: "polite",
  },
  {
    id: "p-29",
    japanese: "まっすぐ行ってください。",
    hiragana: "まっすぐいってください。",
    romaji: "Massugu itte kudasai.",
    english: "Please go straight ahead.",
    vietnamese: "Xin hãy đi thẳng.",
    theme: "travel",
    topic: "asking_directions",
    formality: "polite",
  },
  {
    id: "p-30",
    japanese: "右に曲がってください。",
    hiragana: "みぎにまがってください。",
    romaji: "Migi ni magatte kudasai.",
    english: "Please turn right.",
    vietnamese: "Xin hãy rẽ phải.",
    theme: "travel",
    topic: "asking_directions",
    formality: "polite",
  },
  {
    id: "p-31",
    japanese: "左に曲がってください。",
    hiragana: "ひだりにまがってください。",
    romaji: "Hidari ni magatte kudasai.",
    english: "Please turn left.",
    vietnamese: "Xin hãy rẽ trái.",
    theme: "travel",
    topic: "asking_directions",
    formality: "polite",
  },
  {
    id: "p-32",
    japanese: "歩いてどのくらいですか？",
    hiragana: "あるいてどのくらいですか？",
    romaji: "Aruite dono kurai desu ka?",
    english: "How long does it take on foot?",
    vietnamese: "Đi bộ mất bao lâu?",
    theme: "travel",
    topic: "asking_directions",
    formality: "polite",
  },
  {
    id: "p-33",
    japanese: "地図を描いていただけますか？",
    hiragana: "ちずをかいていただけますか？",
    romaji: "Chizu wo kaite itadakemasu ka?",
    english: "Could you draw a map for me?",
    vietnamese: "Bạn vẽ giúp tôi bản đồ được không?",
    theme: "travel",
    topic: "asking_directions",
    formality: "polite",
  },

  // --- 2. TRAVEL & DIRECTIONS: Trains & Transport ---
  {
    id: "p-34",
    japanese: "東京行きのお切符を一枚ください。",
    hiragana: "とうきょうゆきのおきっぷをいちまいください。",
    romaji: "Toukyou yuki no o-kippu wo ichimai kudasai.",
    english: "One ticket to Tokyo, please.",
    vietnamese: "Cho tôi một vé đi Tokyo.",
    theme: "travel",
    topic: "transportation",
    formality: "polite",
  },
  {
    id: "p-35",
    japanese: "この電車は新宿に行きますか？",
    hiragana: "このでんしゃはしんじゅくにいきますか？",
    romaji: "Kono densha wa Shinjuku ni ikimasu ka?",
    english: "Does this train go to Shinjuku?",
    vietnamese: "Tàu này có đi đến Shinjuku không?",
    theme: "travel",
    topic: "transportation",
    formality: "polite",
  },
  {
    id: "p-36",
    japanese: "何番線ですか？",
    hiragana: "なんばんせんですか？",
    romaji: "Nanbansen desu ka?",
    english: "Which track / platform is it?",
    vietnamese: "Ở đường sắt số mấy vậy?",
    theme: "travel",
    topic: "transportation",
    formality: "polite",
  },
  {
    id: "p-37",
    japanese: "タクシー乗り場はどこですか？",
    hiragana: "たくしーのりばはどこですか？",
    romaji: "Takushii noriba wa doko desu ka?",
    english: "Where is the taxi stand?",
    vietnamese: "Điểm đón taxi ở đâu?",
    theme: "travel",
    topic: "transportation",
    formality: "polite",
  },
  {
    id: "p-38",
    japanese: "ここまでお願いします。",
    hiragana: "ここまでおねがいします。",
    romaji: "Koko made onegaishimasu.",
    english: "To this place, please (to taxi driver).",
    vietnamese: "Cho tôi đến chỗ này nhé (nói với tài xế taxi).",
    theme: "travel",
    topic: "transportation",
    formality: "polite",
  },

  // --- 3. DINING & SHOPPING: Restaurant & Ordering ---
  {
    id: "p-39",
    japanese: "いらっしゃいませ！",
    hiragana: "いらっしゃいませ！",
    romaji: "Irasshaimase!",
    english: "Welcome!",
    vietnamese: "Xin kính chào quý khách!",
    theme: "dining_shopping",
    topic: "restaurant_dining",
    formality: "formal",
    notesEn: "Staff greeting when entering shops or restaurants.",
    notesVi: "Lời chào của nhân viên khi bạn vào cửa hàng/nhà hàng.",
  },
  {
    id: "p-40",
    japanese: "何名様ですか？",
    hiragana: "なんめいさまですか？",
    romaji: "Nanmeisama desu ka?",
    english: "How many people in your party?",
    vietnamese: "Quý khách đi mấy người?",
    theme: "dining_shopping",
    topic: "restaurant_dining",
    formality: "formal",
  },
  {
    id: "p-41",
    japanese: "二人です。",
    hiragana: "ふたりです。",
    romaji: "Futari desu.",
    english: "Two people.",
    vietnamese: "Hai người.",
    theme: "dining_shopping",
    topic: "restaurant_dining",
    formality: "polite",
  },
  {
    id: "p-42",
    japanese: "メニューをいただけますか？",
    hiragana: "めにゅーをいただけますか？",
    romaji: "Menyuu wo itadakemasu ka?",
    english: "Could I get a menu, please?",
    vietnamese: "Cho tôi xin thực đơn được không?",
    theme: "dining_shopping",
    topic: "restaurant_dining",
    formality: "polite",
  },
  {
    id: "p-43",
    japanese: "これをお願いします。",
    hiragana: "これををおねがいします。",
    romaji: "Kore wo onegaishimasu.",
    english: "This one, please.",
    vietnamese: "Cho tôi món này nhé.",
    theme: "dining_shopping",
    topic: "restaurant_dining",
    formality: "polite",
  },
  {
    id: "p-44",
    japanese: "お水をもらえますか？",
    hiragana: "おみずをもらえますか？",
    romaji: "O-mizu wo moraemasu ka?",
    english: "Can I have some water, please?",
    vietnamese: "Cho tôi xin ly nước lọc được không?",
    theme: "dining_shopping",
    topic: "restaurant_dining",
    formality: "polite",
  },
  {
    id: "p-45",
    japanese: "お会計をお願いします。",
    hiragana: "おかいけいををおねがいします。",
    romaji: "O-kaikei wo onegaishimasu.",
    english: "The bill, please.",
    vietnamese: "Tính tiền giúp tôi.",
    theme: "dining_shopping",
    topic: "restaurant_dining",
    formality: "polite",
  },
  {
    id: "p-46",
    japanese: "ごちそうさまでした。",
    hiragana: "ごちそうさまでした。",
    romaji: "Gochisousama deshita.",
    english: "Thank you for the meal.",
    vietnamese: "Cảm ơn vì bữa ăn ngon.",
    theme: "dining_shopping",
    topic: "restaurant_dining",
    formality: "polite",
  },

  // --- 3. DINING & SHOPPING: Shopping & Prices ---
  {
    id: "p-47",
    japanese: "いくらですか？",
    hiragana: "いくらですか？",
    romaji: "Ikura desu ka?",
    english: "How much is it?",
    vietnamese: "Cái này bao nhiêu tiền?",
    theme: "dining_shopping",
    topic: "shopping_prices",
    formality: "polite",
  },
  {
    id: "p-48",
    japanese: "試着してもいいですか？",
    hiragana: "しちゃくしてもいいですか？",
    romaji: "Shichaku shitemo ii desu ka?",
    english: "May I try this on?",
    vietnamese: "Tôi thử cái này được không?",
    theme: "dining_shopping",
    topic: "shopping_prices",
    formality: "polite",
  },
  {
    id: "p-49",
    japanese: "これのMサイズはありますか？",
    hiragana: "これのMさいずはありますか？",
    romaji: "Kore no M saizu wa arimasu ka?",
    english: "Do you have this in size M?",
    vietnamese: "Mẫu này có size M không?",
    theme: "dining_shopping",
    topic: "shopping_prices",
    formality: "polite",
  },
  {
    id: "p-50",
    japanese: "免税できますか？",
    hiragana: "めんぜいできますか？",
    romaji: "Menzei dekimasu ka?",
    english: "Is this duty-free?",
    vietnamese: "Cái này có được miễn thuế không?",
    theme: "dining_shopping",
    topic: "shopping_prices",
    formality: "polite",
  },
  {
    id: "p-51",
    japanese: "クレジットカードは使えますか？",
    hiragana: "くれじっとかーどはつかえますか？",
    romaji: "Kurejitto kaado wa tsukaemasu ka?",
    english: "Can I use a credit card?",
    vietnamese: "Có thể dùng thẻ tín dụng không?",
    theme: "dining_shopping",
    topic: "shopping_prices",
    formality: "polite",
  },
  {
    id: "p-52",
    japanese: "袋をいただけますか？",
    hiragana: "ふくろをいただけますか？",
    romaji: "Fukuro wo itadakemasu ka?",
    english: "Could I have a plastic bag?",
    vietnamese: "Cho tôi xin túi nilon được không?",
    theme: "dining_shopping",
    topic: "shopping_prices",
    formality: "polite",
  },

  // --- 4. SCHOOL & STUDY: Classroom Expressions ---
  {
    id: "p-53",
    japanese: "質問があります。",
    hiragana: "しつもんがあります。",
    romaji: "Shitsumon ga arimasu.",
    english: "I have a question.",
    vietnamese: "Tôi có một câu hỏi.",
    theme: "school_study",
    topic: "classroom_study",
    formality: "polite",
  },
  {
    id: "p-54",
    japanese: "もう一度言ってください。",
    hiragana: "もういちどいってください。",
    romaji: "Mou ichido itte kudasai.",
    english: "Please say it once more.",
    vietnamese: "Xin hãy nói lại lần nữa.",
    theme: "school_study",
    topic: "classroom_study",
    formality: "polite",
  },
  {
    id: "p-55",
    japanese: "ゆっくり話してください。",
    hiragana: "ゆっくりはなしてください。",
    romaji: "Yukkuri hanashite kudasai.",
    english: "Please speak slowly.",
    vietnamese: "Xin hãy nói chậm lại.",
    theme: "school_study",
    topic: "classroom_study",
    formality: "polite",
  },
  {
    id: "p-56",
    japanese: "書いていただけますか？",
    hiragana: "かいていただけますか？",
    romaji: "Kaite itadakemasu ka?",
    english: "Could you write it down for me?",
    vietnamese: "Bạn viết ra giúp tôi được không?",
    theme: "school_study",
    topic: "classroom_study",
    formality: "polite",
  },
  {
    id: "p-57",
    japanese: "わかりました。",
    hiragana: "わかりました。",
    romaji: "Wakarimashita.",
    english: "I understand.",
    vietnamese: "Tôi đã hiểu rồi.",
    theme: "school_study",
    topic: "classroom_study",
    formality: "polite",
  },
  {
    id: "p-58",
    japanese: "わかりません。",
    hiragana: "わかりません。",
    romaji: "Wakarimasen.",
    english: "I don't understand.",
    vietnamese: "Tôi không hiểu.",
    theme: "school_study",
    topic: "classroom_study",
    formality: "polite",
  },

  // --- 4. SCHOOL & STUDY: Asking Questions ---
  {
    id: "p-59",
    japanese: "日本語で何と言いますか？",
    hiragana: "にほんごでなんといいますか？",
    romaji: "Nihongo de nan to iimasu ka?",
    english: "How do you say this in Japanese?",
    vietnamese: "Nói câu này bằng tiếng Nhật như thế nào?",
    theme: "school_study",
    topic: "asking_questions",
    formality: "polite",
  },
  {
    id: "p-60",
    japanese: "〜はどういう意味ですか？",
    hiragana: "〜はどういういみですか？",
    romaji: "... wa douiu imi desu ka?",
    english: "What does ... mean?",
    vietnamese: "... có nghĩa là gì?",
    theme: "school_study",
    topic: "asking_questions",
    formality: "polite",
  },
  {
    id: "p-61",
    japanese: "英語を話せますか？",
    hiragana: "えいごをはなせますか？",
    romaji: "Eigo wo hanasemasu ka?",
    english: "Can you speak English?",
    vietnamese: "Bạn có nói được tiếng Anh không?",
    theme: "school_study",
    topic: "asking_questions",
    formality: "polite",
  },
  {
    id: "p-62",
    japanese: "正しいですか？",
    hiragana: "ただしいですか？",
    romaji: "Tadashii desu ka?",
    english: "Is this correct?",
    vietnamese: "Như thế này có đúng không?",
    theme: "school_study",
    topic: "asking_questions",
    formality: "polite",
  },

  // --- 5. WORK & OFFICE: Office Expressions ---
  {
    id: "p-63",
    japanese: "お疲れ様です。",
    hiragana: "おつかれさまです。",
    romaji: "Otsukaresama desu.",
    english: "Thank you for your hard work.",
    vietnamese: "Bạn đã làm việc vất vả rồi.",
    theme: "work_business",
    topic: "workplace_office",
    formality: "polite",
    notesEn: "Standard greeting between coworkers during or after work.",
    notesVi: "Lời chào chuẩn giữa đồng nghiệp trong và sau giờ làm.",
  },
  {
    id: "p-64",
    japanese: "お先に失礼します。",
    hiragana: "おさきにしつれいします。",
    romaji: "Osaki ni shitsurei shimasu.",
    english: "I am leaving first / See you tomorrow.",
    vietnamese: "Tôi xin phép về trước.",
    theme: "work_business",
    topic: "workplace_office",
    formality: "polite",
    notesEn: "Said when leaving the office before others.",
    notesVi: "Nói khi ra về trước các đồng nghiệp khác.",
  },
  {
    id: "p-65",
    japanese: "少々お待ちください。",
    hiragana: "しょうしょうおまちください。",
    romaji: "Shoushou omachi kudasai.",
    english: "Please wait a moment.",
    vietnamese: "Xin vui lòng đợi một chút.",
    theme: "work_business",
    topic: "workplace_office",
    formality: "formal",
  },
  {
    id: "p-66",
    japanese: "承知いたしました。",
    hiragana: "しょうちいたしました。",
    romaji: "Shouchi itashimashita.",
    english: "Certainly / Understood (to clients/superiors).",
    vietnamese: "Tôi đã hiểu rõ (nói với cấp trên/khách hàng).",
    theme: "work_business",
    topic: "workplace_office",
    formality: "formal",
  },
  {
    id: "p-67",
    japanese: "確認しますので、少々お待ちください。",
    hiragana: "かくにんしますので、しょうしょうおまちください。",
    romaji: "Kakunin shimasu node, shoushou omachi kudasai.",
    english: "I will check, please wait a moment.",
    vietnamese: "Tôi sẽ kiểm tra lại, xin vui lòng đợi một chút.",
    theme: "work_business",
    topic: "workplace_office",
    formality: "formal",
  },
  {
    id: "p-68",
    japanese: "よろしくおねがいいたします。",
    hiragana: "よろしくおねがいいたします。",
    romaji: "Yoroshiku onegai itashimasu.",
    english: "Best regards / I look forward to working with you.",
    vietnamese: "Rất mong nhận được sự hợp tác của quý vị.",
    theme: "work_business",
    topic: "workplace_office",
    formality: "formal",
  },

  // --- 6. HEALTH & EMERGENCY: Medical & Emergencies ---
  {
    id: "p-69",
    japanese: "助けてください！",
    hiragana: "たすけてください！",
    romaji: "Tasukete kudasai!",
    english: "Help me, please!",
    vietnamese: "Xin hãy cứu tôi với!",
    theme: "emergency",
    topic: "health_emergency",
    formality: "polite",
  },
  {
    id: "p-70",
    japanese: "気分が悪いです。",
    hiragana: "きぶんがわるいです。",
    romaji: "Kibun ga warui desu.",
    english: "I feel sick / unwell.",
    vietnamese: "Tôi cảm thấy trong người không khỏe.",
    theme: "emergency",
    topic: "health_emergency",
    formality: "polite",
  },
  {
    id: "p-71",
    japanese: "頭が痛いです。",
    hiragana: "あたまがいたいです。",
    romaji: "Atama ga itai desu.",
    english: "I have a headache.",
    vietnamese: "Tôi bị đau đầu.",
    theme: "emergency",
    topic: "health_emergency",
    formality: "polite",
  },
  {
    id: "p-72",
    japanese: "熱があります。",
    hiragana: "ねつがあります。",
    romaji: "Netsu ga arimasu.",
    english: "I have a fever.",
    vietnamese: "Tôi bị sốt.",
    theme: "emergency",
    topic: "health_emergency",
    formality: "polite",
  },
  {
    id: "p-73",
    japanese: "薬をください。",
    hiragana: "くすりをください。",
    romaji: "Kusuri wo kudasai.",
    english: "Please give me medicine.",
    vietnamese: "Cho tôi xin thuốc.",
    theme: "emergency",
    topic: "health_emergency",
    formality: "polite",
  },
  {
    id: "p-74",
    japanese: "病院に行きたいです。",
    hiragana: "びょういんにいきたいです。",
    romaji: "Byouin ni ikitai desu.",
    english: "I want to go to the hospital.",
    vietnamese: "Tôi muốn đi đến bệnh viện.",
    theme: "emergency",
    topic: "health_emergency",
    formality: "polite",
  },
  {
    id: "p-75",
    japanese: "救急車を呼んでください！",
    hiragana: "きゅうきゅうしゃをよんでください！",
    romaji: "Kyuukyuusha wo yonde kudasai!",
    english: "Please call an ambulance!",
    vietnamese: "Xin hãy gọi xe cấp cứu giúp tôi!",
    theme: "emergency",
    topic: "health_emergency",
    formality: "polite",
  },
  {
    id: "p-76",
    japanese: "パスポートをなくしました。",
    hiragana: "ぱすぽーとをなくしました。",
    romaji: "Pasupooto wo nakushimashita.",
    english: "I lost my passport.",
    vietnamese: "Tôi bị mất hộ chiếu rồi.",
    theme: "emergency",
    topic: "health_emergency",
    formality: "polite",
  },
  {
    id: "p-77",
    japanese: "警察を呼んでください！",
    hiragana: "けいさつをよんでください！",
    romaji: "Keisatsu wo yonde kudasai!",
    english: "Please call the police!",
    vietnamese: "Xin hãy gọi cảnh sát giúp tôi!",
    theme: "emergency",
    topic: "health_emergency",
    formality: "polite",
  },
];
