import type { TeachingSlide } from "./teaching-deck";

/**
 * Digitized from "bài 1-25.pdf" (129 slides, 1 slide per PDF page, original order
 * preserved). Teachers can Add/Edit/Duplicate/Delete/Reorder any slide from the
 * Teaching tab — this is just the starting deck.
 */
export const MINNA_LESSON_SLIDES: TeachingSlide[] = [
  // ===== だい1か (p.1-11) =====
  {
    id: "p001",
    title: "だい1か",
    subtitle: "Bảng chữ cái Hiragana — Trọc âm, ghép âm, xúc âm, trường âm",
    type: "title",
    japanese: "だい１か",
    romaji: "Dai ikka",
    translation: "Bài 1",
    theme: "indigo",
  },
  {
    id: "p002",
    title: "Trọc âm (Dakuten) & Bán trọc âm (Handakuten)",
    subtitle: "が° = Tenten ／ ぱ° = Maru",
    type: "kana_grid",
    japanese: "K が ぎ ぐ げ ご　S ざ じ ず ぜ ぞ　T だ ぢ づ で ど　H ば び ぶ べ ぼ　H ぱ ぴ ぷ ぺ ぽ",
    romaji: "ga gi gu ge go / za ji zu ze zo / da ji zu de do / ba bi bu be bo / pa pi pu pe po",
    bullets: [
      "が゛ gọi là Tenten — thêm vào hàng か・さ・た・は để tạo âm đục (g/z/d/b)",
      "ぱ゜ gọi là Maru — chỉ thêm vào hàng は để tạo âm bán đục (p)",
    ],
    theme: "indigo",
  },
  {
    id: "p003",
    title: "Ghép い",
    subtitle: "い ghép được với 3 cột あ・う・お (kể cả bảng trọc âm), trừ を、ん",
    type: "kana_grid",
    japanese: "あい・すい・たい・ない・まい・むい・もい ...",
    bullets: [
      "い ghép được với 3 cột あ・う・お (bao gồm luôn bảng trọc âm), ngoại trừ を、ん",
    ],
    theme: "indigo",
  },
  {
    id: "p004",
    title: "Ghép ん",
    subtitle: "Đọc là 'n', đổi thành 'm' trước 15 âm môi",
    type: "kana_grid",
    japanese: "にほん・こんばん",
    romaji: "nihon, konban",
    bullets: [
      "ん ghép được với tất cả những chữ trong bảng chữ (bao gồm bảng trọc âm), ngoại trừ を và chính nó",
      "Đa số đọc là n; đọc là m khi đứng trước 15 âm môi: ま・み・む・め・も／ば・び・ぶ・べ・ぼ／ぱ・ぴ・ぷ・ぺ・ぽ",
      "Ví dụ: にほん (n bình thường), こんばん (đọc gần 'komban' vì đứng trước ば)",
    ],
    theme: "indigo",
  },
  {
    id: "p005",
    title: "Xúc âm っ",
    subtitle: "Âm ngắt: っ nhỏ đứng trước phụ âm",
    type: "kana_grid",
    japanese: "きって・ざっし",
    romaji: "kitte, zasshi",
    theme: "indigo",
  },
  {
    id: "p006",
    title: "Trường âm",
    subtitle: "5 nguyên âm あ・い・う・え・お làm trường âm cho chính cột của mình",
    type: "kana_grid",
    japanese: "おかあさん・おとうさん",
    romaji: "okaasan, otousan",
    bullets: [
      "5 nguyên âm chính あいうえお làm trường âm cho nó và cột của chính nó, ngoại trừ を、ん",
      "い còn làm trường âm cho cột え; う còn làm trường âm cho cột お",
    ],
    theme: "indigo",
  },
  {
    id: "p007",
    title: "N1は N2です。",
    subtitle: "N1 là N2",
    type: "grammar",
    japanese: "わたしは せんせいです。",
    romaji: "Watashi wa sensei desu.",
    translation: "Tôi là giáo viên.",
    bullets: [
      "N: danh từ",
      "は là trợ từ, đọc biến âm là わ",
    ],
    theme: "indigo",
  },
  {
    id: "p008",
    title: "N1は N2ではありません。",
    subtitle: "N1 không phải là N2 — では(văn viết) / じゃ(văn nói)",
    type: "grammar",
    japanese: "わたしは いしゃでは（じゃ）ありません。",
    romaji: "Watashi wa isha dewa (ja) arimasen.",
    translation: "Tôi không phải là bác sĩ.",
    theme: "indigo",
  },
  {
    id: "p009",
    title: "Câu hỏi xác nhận thông tin",
    subtitle: "N1は N2ですか。",
    type: "grammar",
    japanese: "さくらさんは がくせいですか。",
    romaji: "Sakura-san wa gakusei desu ka.",
    translation: "Bạn Sakura có phải là sinh viên không?",
    bullets: [
      "はい、…です。／ はい、そうです。(Vâng, đúng vậy)",
      "いいえ、…では(じゃ)ありません。／ そうでは(じゃ)ありません。／ ちがいます。(Không, sai rồi)",
    ],
    theme: "indigo",
  },
  {
    id: "p010",
    title: "Câu hỏi nghi vấn từ & câu hỏi lựa chọn",
    subtitle: "あのひとは だれですか。／ N1ですか、N2ですか。",
    type: "grammar",
    japanese: "あのひとは だれですか。\nボールペンですか、シャープペンシルですか。",
    romaji: "Ano hito wa dare desu ka. / Boorupen desu ka, shaapupenshiru desu ka.",
    translation: "Người kia là ai? / Là bút bi hay bút chì bấm?",
    bullets: [
      "Câu hỏi nghi vấn từ: あのひとは だれですか。→ イーさんです。",
      "Câu hỏi lựa chọn (hay là/hoặc là): N1ですか、N2ですか。→ N1/N2です。",
    ],
    theme: "indigo",
  },
  {
    id: "p011",
    title: "も & N1のN2",
    subtitle: "も = cũng ／ の nối 2 danh từ",
    type: "grammar",
    japanese: "わたしは ぎんこういんです。あなたも ぎんこういんですか。\nさくらだいがくの きょうしです。",
    romaji: "Watashi wa ginkouin desu. Anata mo ginkouin desu ka. / Sakura daigaku no kyoushi desu.",
    translation: "Tôi là nhân viên ngân hàng. Bạn cũng là nhân viên ngân hàng à? / (Tôi là) giáo viên trường đại học Sakura.",
    bullets: [
      "も: cũng (trợ từ)",
      "N1のN2: の là trợ từ nối 2 danh từ, danh từ 2 là danh từ chính",
    ],
    theme: "indigo",
  },

  // ===== だい2か (p.12-14) =====
  {
    id: "p012",
    title: "だい2か",
    subtitle: "これ・それ・あれ ／ N1のN2",
    type: "title",
    japanese: "だい２か",
    romaji: "Dai nikka",
    translation: "Bài 2",
    theme: "emerald",
  },
  {
    id: "p013",
    title: "これ・それ・あれ・どれ",
    subtitle: "この・その・あの・どの + N",
    type: "grammar",
    japanese: "これは かぎです。\nかぎは これです。",
    romaji: "Kore wa kagi desu. / Kagi wa kore desu.",
    translation: "Cái này là chìa khóa. / Chìa khóa là cái này.",
    bullets: [
      "これ/それ/あれ は N(đồ vật)です。= Cái này/đó/kia là N; なんですか。= Cái gì?",
      "N(đồ vật)は これ/それ/あれです。= N là cái này/đó/kia; どれですか。= Cái nào?",
      "この/その/あの/どの + N (danh từ đi kèm)",
    ],
    theme: "emerald",
  },
  {
    id: "p014",
    title: "N1のN2",
    subtitle: "Trực thuộc・Bổ nghĩa・Sở hữu",
    type: "grammar",
    japanese: "さくらだいがくの がくせいです。\nにほんごの ほんです。\nわたしの ほんです。",
    romaji: "Sakura daigaku no gakusei desu. / Nihongo no hon desu. / Watashi no hon desu.",
    translation: "Sinh viên trường đại học Sakura. / Sách tiếng Nhật. / Sách của tôi.",
    bullets: [
      "Trực thuộc: さくらだいがくのがくせいです。(Sinh viên trường ĐH Sakura)",
      "Bổ nghĩa: にほんごのほんです。(Sách Tiếng Nhật) — なんですか。Sách gì?",
      "Sở hữu: わたしのほんです。(Sách của tôi) — だれのですか。Sách của ai?",
      "このほんは わたしのほんです。→ rút gọn: このほんは わたしのです。",
    ],
    theme: "emerald",
  },

  // ===== だい3か (p.15-19) =====
  {
    id: "p015",
    title: "だい3か",
    subtitle: "ここ・そこ・あそこ ／ Địa điểm & xuất xứ",
    type: "title",
    japanese: "だい３か",
    romaji: "Dai sankka",
    translation: "Bài 3",
    theme: "amber",
  },
  {
    id: "p016",
    title: "ここ・そこ・あそこ・どこ",
    subtitle: "Chỗ này/đó/kia là N(địa điểm)",
    type: "grammar",
    japanese: "ここは きょうしつです。\nきょうしつは ここです。",
    romaji: "Koko wa kyoushitsu desu. / Kyoushitsu wa koko desu.",
    translation: "Đây là phòng học. / Phòng học ở đây.",
    bullets: [
      "ここ／そこ／あそこ は N(địa điểm)です。／ N(địa điểm)は ここ／そこ／あそこです。",
      "どこですか。= Chỗ nào?",
    ],
    theme: "amber",
  },
  {
    id: "p017",
    title: "N1は N2(địa điểm)です。",
    subtitle: "N1 (vật/người/địa điểm) ở địa điểm nào",
    type: "grammar",
    japanese: "くるまの かぎは へやです。\nAさんは うけつけです。\nトイレは いっかいです。",
    romaji: "Kuruma no kagi wa heya desu. / A-san wa uketsuke desu. / Toire wa ikkai desu.",
    translation: "Chìa khóa xe ở trong phòng. / Anh A ở quầy lễ tân. / Nhà vệ sinh ở tầng 1.",
    bullets: [
      "N1(vật/người/địa điểm)は N2(địa điểm)です。 — どこですか。 chỗ nào?",
    ],
    theme: "amber",
  },
  {
    id: "p018",
    title: "N1(tên nước/công ty)のN2(sản phẩm)",
    subtitle: "Sản phẩm được sản xuất ở nước/công ty nào",
    type: "grammar",
    japanese: "にほんの とけいです。\nドイツの じどうしゃです。",
    romaji: "Nihon no tokei desu. / Doitsu no jidousha desu.",
    translation: "Đồng hồ của Nhật. / Ô tô của Đức.",
    bullets: ["どこのN(sản phẩm)ですか。— hỏi xuất xứ sản phẩm"],
    theme: "amber",
  },
  {
    id: "p019",
    title: "おくには どちらですか。",
    subtitle: "どちら lịch sự hơn どこ khi hỏi quốc gia/công ty",
    type: "grammar",
    japanese: "おくには どちらですか。…（くには）にほんです。\nかいしゃ(がっこう)は どちらですか。…（かいしゃは）IMCです。",
    romaji: "Okuni wa dochira desu ka. ... (Kuni wa) Nihon desu. / Kaisha (gakkou) wa dochira desu ka. ... (Kaisha wa) IMC desu.",
    translation: "Quê bạn ở đâu? ...(Quê tôi) ở Nhật. / Công ty (trường) bạn ở đâu? ...(Công ty tôi) là IMC.",
    theme: "amber",
  },

  // ===== だい4か (p.20-23) =====
  {
    id: "p020",
    title: "だい4か",
    subtitle: "Thì của động từ & giờ giấc",
    type: "title",
    japanese: "だい４か",
    romaji: "Dai yonka",
    translation: "Bài 4",
    theme: "rose",
  },
  {
    id: "p021",
    title: "V ます／ません／ました／ませんでした",
    subtitle: "Hiện tại/tương lai & quá khứ, khẳng định/phủ định",
    type: "grammar",
    japanese: "はたらきます。／ はたらきません。\nはたらきました。／ はたらきませんでした。",
    romaji: "Hatarakimasu / hatarakimasen / hatarakimashita / hatarakimasendeshita.",
    translation: "Làm việc (sẽ) / không làm việc / đã làm việc / đã không làm việc.",
    bullets: [
      "ます: hiện tại/tương lai khẳng định — ません: phủ định",
      "ました: quá khứ khẳng định — ませんでした: quá khứ phủ định",
    ],
    theme: "rose",
  },
  {
    id: "p022",
    title: "Danh từ chỉ thời gian & …から…まで",
    subtitle: "Thời gian xác định + に ／ không xác định không cần に",
    type: "grammar",
    japanese: "…から　…まで",
    translation: "từ … đến …",
    bullets: [
      "Danh từ chỉ thời gian xác định (giờ/ngày/tháng cụ thể) + に",
      "Danh từ chỉ thời gian không xác định (きょう, あした...) không cần に",
    ],
    theme: "rose",
  },
  {
    id: "p023",
    title: "Hỏi giờ giấc",
    subtitle: "なんじから なんじまで／なんじに",
    type: "grammar",
    japanese: "ぎんこうは なんじから なんじまで ですか。…7じから 4じはんまでです。\nけさ なんじに おきましたか。…けさ 5じに おきました。",
    romaji: "Ginkou wa nanji kara nanji made desu ka. ... 7-ji kara 4-ji han made desu. / Kesa nanji ni okimashita ka. ... Kesa 5-ji ni okimashita.",
    translation: "Ngân hàng mở cửa từ mấy giờ đến mấy giờ? ...Từ 7 giờ đến 4 rưỡi. / Sáng nay bạn thức dậy lúc mấy giờ? ...Sáng nay tôi thức dậy lúc 5 giờ.",
    theme: "rose",
  },

  // ===== だい5か (p.24-25) =====
  {
    id: "p024",
    title: "だい5か",
    subtitle: "N(địa điểm)へ 行きます・来ます・帰ります",
    type: "title",
    japanese: "だい５か",
    romaji: "Dai gokka",
    translation: "Bài 5",
    theme: "dark",
  },
  {
    id: "p025",
    title: "Sは N(địa điểm)へ 行きます／来ます／帰ります",
    subtitle: "Người/vật đi cùng と ・ phương tiện で",
    type: "grammar",
    japanese: "わたしは らいねん ともだちと ひこうきで にほんへ いきます。",
    romaji: "Watashi wa rainen tomodachi to hikouki de nihon e ikimasu.",
    translation: "Sang năm tôi sẽ đi Nhật cùng bạn bằng máy bay.",
    bullets: [
      "N(người/vật)と = cùng ai; N(phương tiện)で = bằng gì; N(địa điểm)へ = đến đâu; ひとりで = một mình",
      "Phủ định: どこ(へ)も いきません／いきませんでした",
      "Câu hỏi: いつ・だれと・なんで・どこへ + V thể ますか。",
    ],
    theme: "dark",
  },

  // ===== だい6か (p.26-30) =====
  {
    id: "p026",
    title: "だい6か",
    subtitle: "Tha động từ, lời mời, rủ rê",
    type: "title",
    japanese: "だい６か",
    romaji: "Dai rokka",
    translation: "Bài 6",
    theme: "indigo",
  },
  {
    id: "p027",
    title: "Nを V ／ ひとに あいます",
    subtitle: "Tha động từ (ngoại động từ)",
    type: "grammar",
    japanese: "やさいを たべます。\nひとに あいます。\nしゅくだいを します。",
    romaji: "Yasai o tabemasu. / Hito ni aimasu. / Shukudai o shimasu.",
    translation: "Ăn rau. / Gặp người. / Làm bài tập.",
    bullets: [
      "Nを V(tha động từ): なにも たべません = không ăn gì cả",
      "✔ ひとに あいます (gặp…): だれにも あいません = không gặp ai cả",
      "Nを します。(làm/chơi…): なにも しません = không làm gì cả",
    ],
    theme: "indigo",
  },
  {
    id: "p028",
    title: "N(địa điểm)で V ／ Vませんか・ましょう",
    subtitle: "Địa điểm hành động & rủ rê",
    type: "grammar",
    japanese: "うちで べんきょうします。\nいっしょに えいがを みませんか。",
    romaji: "Uchi de benkyoushimasu. / Issho ni eiga o mimasen ka.",
    translation: "Học ở nhà. / Cùng xem phim nhé?",
    bullets: [
      "N(địa điểm)で V(hành động): どこで…か。",
      "Vませんか。= rủ rê; Vましょう。= rủ cùng làm",
      "Đáp lại: はい、みましょう。／ いいですね。／ いいですよ。／ すみません。ちょっと…",
    ],
    theme: "indigo",
  },
  {
    id: "p029",
    title: "なんと・なんの・なんで・なんさい",
    subtitle: "Còn lại là なに",
    type: "grammar",
    japanese: "なんと・なんの・なんで（なにで）・なんさい",
    bullets: ["Còn lại (đứng trước từ khác) đọc là なに"],
    theme: "indigo",
  },
  {
    id: "p030",
    title: "Ôn tập: Sは N(địa điểm)へ いきます",
    subtitle: "Bảng tổng hợp: いつ・だれと・なんで(なにで)・どこへ",
    type: "grammar",
    japanese: "わたしは らいねん ともだちと ひこうきで にほんへ いきます。",
    romaji: "Watashi wa rainen tomodachi to hikouki de nihon e ikimasu.",
    translation: "Sang năm tôi sẽ đi Nhật cùng bạn bằng máy bay.",
    bullets: [
      "…から…まで／ ひとりで／ あるいて(で) đều dùng được trước 行きます・来ます・帰ります",
      "Câu hỏi bổ sung なんで／なにで (bằng gì) bên cạnh いつ・だれと・どこへ",
    ],
    theme: "indigo",
  },

  // ===== だい7か (p.31-37) =====
  {
    id: "p031",
    title: "だい7か",
    subtitle: "Công cụ で ・ Cho/tặng/nhận",
    type: "title",
    japanese: "だい７か",
    romaji: "Dai nanakka",
    translation: "Bài 7",
    theme: "emerald",
  },
  {
    id: "p032",
    title: "N(công cụ, dụng cụ)で V",
    subtitle: "Bằng…",
    type: "grammar",
    japanese: "はしで たべます。\nにほんごで レポートを かきます。",
    romaji: "Hashi de tabemasu. / Nihongo de repooto o kakimasu.",
    translation: "Ăn bằng đũa. / Viết báo cáo bằng tiếng Nhật.",
    bullets: ["Hỏi bằng なんで"],
    theme: "emerald",
  },
  {
    id: "p033",
    title: "「Từ/Câu」は …ごで なんですか。",
    subtitle: "Tiếng…nói thế nào?",
    type: "grammar",
    japanese: "「ありがとう」は ベトナムごで なんですか。…cảm ơん です。\n「Chào buổi sáng」は にほんごで なんですか。…おはようございます です。",
    translation: "'Cảm ơn' tiếng Việt nói thế nào? ...là 'cảm ơn'. / 'Chào buổi sáng' tiếng Nhật nói thế nào? ...là 'おはようございます'.",
    theme: "emerald",
  },
  {
    id: "p034",
    title: "あげます",
    subtitle: "Mình/người khác tặng cho người khác 1 đồ vật",
    type: "grammar",
    japanese: "わたしは たなかさんに にほんごのほんを あげます。\nやまださんは きむらさんに はなを あげました。",
    romaji: "Watashi wa Tanaka-san ni nihongo no hon o agemasu. / Yamada-san wa Kimura-san ni hana o agemashita.",
    translation: "Tôi tặng anh Tanaka quyển sách tiếng Nhật. / Anh Yamada đã tặng anh Kimura hoa.",
    bullets: [
      "ひとに ものを かします(cho mượn)／おしえます(dạy)／かきます(viết cho)／おくります(gửi)",
      "ひとに でんわを かけます／でんわします (gọi điện thoại cho ai)",
    ],
    theme: "emerald",
  },
  {
    id: "p035",
    title: "もらいます",
    subtitle: "Mình/người khác nhận từ người khác 1 đồ vật",
    type: "grammar",
    japanese: "わたしは ちちに とけいを もらいました。\nきむらさんは やまださんに はなを もらいました。",
    romaji: "Watashi wa chichi ni tokei o moraimashita. / Kimura-san wa Yamada-san ni hana o moraimashita.",
    translation: "Tôi nhận đồng hồ từ bố. / Anh Kimura nhận hoa từ anh Yamada.",
    bullets: ["人に/から ものを かります(mượn)／ならいます(học từ ai)"],
    theme: "emerald",
  },
  {
    id: "p036",
    title: "くれます",
    subtitle: "Người khác tặng/cho mình (hoặc người thân) 1 đồ vật",
    type: "grammar",
    japanese: "さとうさんは わたしに シャツを くれました。\nきむらさんは ちちに ワインを くれました。",
    romaji: "Satou-san wa watashi ni shatsu o kuremashita. / Kimura-san wa chichi ni wain o kuremashita.",
    translation: "Anh Sato đã tặng tôi áo sơ mi. / Anh Kimura đã tặng bố tôi rượu vang.",
    theme: "emerald",
  },
  {
    id: "p037",
    title: "もう…ましたか。",
    subtitle: "Đã…chưa?",
    type: "grammar",
    japanese: "もう ひるごはんを たべましたか。",
    romaji: "Mou hirugohan o tabemashita ka.",
    translation: "Bạn đã ăn trưa chưa?",
    bullets: ["はい、もう …ました。(Vâng, đã…rồi)", "いいえ、まだです。(Chưa)"],
    theme: "emerald",
  },

  // ===== だい8か (p.38-46) =====
  {
    id: "p038",
    title: "だい8か",
    subtitle: "Tính từ い／な & liên từ",
    type: "title",
    japanese: "だい８か",
    romaji: "Dai hakka",
    translation: "Bài 8",
    theme: "amber",
  },
  {
    id: "p039",
    title: "Ôn tập thì động từ",
    subtitle: "V ます／ません／ました／ませんでした",
    type: "grammar",
    japanese: "V ます。／ません。／ました。／ませんでした。",
    theme: "amber",
  },
  {
    id: "p040",
    title: "Tính từ đuôi い",
    subtitle: "です／くないです／かったです／くなかったです",
    type: "grammar",
    japanese: "ひろいです。／ ひろくないです。\nひろかったです。／ ひろくなかったです。",
    romaji: "Hiroi desu / hirokunai desu / hirokatta desu / hirokunakatta desu.",
    translation: "Rộng / không rộng / đã rộng / đã không rộng.",
    bullets: ["Ngoại lệ: いい/よい → よくないです、よかったです、よくなかったです"],
    theme: "amber",
  },
  {
    id: "p041",
    title: "Tính từ な & danh từ",
    subtitle: "です／ではありません／でした／ではありませんでした",
    type: "grammar",
    japanese: "ひまです。／ひまではありません。\nひまでした。／ひまではありませんでした。\nがくせいです。／がくせいではありません。",
    romaji: "Hima desu / hima dewa arimasen / hima deshita / hima dewa arimasendeshita.",
    translation: "Rảnh / không rảnh / đã rảnh / đã không rảnh.",
    theme: "amber",
  },
  {
    id: "p042",
    title: "Sは A どうですか。",
    subtitle: "Hỏi cảm nhận/đánh giá",
    type: "grammar",
    japanese: "ワットせんせいは しんせつです。\nわたしの へやは ひろくないです。\nAさんの くには あついですか。…はい、あついです。／いいえ、あつくないです。",
    romaji: "Watto-sensei wa shinsetsu desu. / Watashi no heya wa hirokunai desu. / A-san no kuni wa atsui desu ka.",
    translation: "Thầy Watt tốt bụng. / Phòng tôi không rộng. / Nước bạn A có nóng không?",
    theme: "amber",
  },
  {
    id: "p043",
    title: "どんな N",
    subtitle: "Aイ N ／ Aナ な N",
    type: "grammar",
    japanese: "ワットせんせいは しんせつなひとです。\nふじさんは たかいやまです。\nコーヒーは おいしいです。→ おいしいコーヒーです。",
    romaji: "Watto-sensei wa shinsetsu na hito desu. / Fujisan wa takai yama desu.",
    translation: "Thầy Watt là người tốt bụng. / Núi Phú Sĩ là ngọn núi cao.",
    theme: "amber",
  },
  {
    id: "p044",
    title: "とても・あまり",
    subtitle: "Phó từ mức độ",
    type: "grammar",
    japanese: "にほんは とても さむいです。\nベトナムは あまり さむくないです。",
    romaji: "Nihon wa totemo samui desu. / Betonamu wa amari samukunai desu.",
    translation: "Nhật rất lạnh. / Việt Nam không lạnh lắm.",
    bullets: ["とても + A(khẳng định) = rất; あまり + A(phủ định) = không…lắm"],
    theme: "amber",
  },
  {
    id: "p045",
    title: "そして・が・でも・しかし",
    subtitle: "Liên từ nối câu",
    type: "grammar",
    japanese: "にほんのたべものは おいしいです。そして、きれいです。\nにほんのたべものは おいしいですが、たかいです。",
    romaji: "Nihon no tabemono wa oishii desu. Soshite, kirei desu. / Nihon no tabemono wa oishii desu ga, takai desu.",
    translation: "Đồ ăn Nhật ngon. Và đẹp mắt. / Đồ ăn Nhật ngon nhưng đắt.",
    bullets: ["そして (và); が (nhưng); でも/しかし cũng là 'nhưng'"],
    theme: "amber",
  },
  {
    id: "p046",
    title: "Ôn tập: これ・それ・あれ・どれ",
    subtitle: "この・その・あの・どの + N",
    type: "grammar",
    japanese: "これ／それ／あれ／どれ\nこの／その／あの／どの + N",
    theme: "amber",
  },

  // ===== だい9か (p.47-50) =====
  {
    id: "p047",
    title: "だい9か",
    subtitle: "すき・きらい・じょうず・へた",
    type: "title",
    japanese: "だい９か",
    romaji: "Dai kyuukka",
    translation: "Bài 9",
    theme: "rose",
  },
  {
    id: "p048",
    title: "Nが すきです・きらいです・じょうずです・へたです",
    subtitle: "だいすき／だいきらい = rất thích/rất ghét",
    type: "grammar",
    japanese: "わたしは タイりょうりが すきです。\nおとうとは さかなが だいきらいです。\nどんなのみものが すきですか。…ジュースが すきです。",
    romaji: "Watashi wa Tai ryouri ga suki desu. / Otouto wa sakana ga daikirai desu.",
    translation: "Tôi thích món ăn Thái. / Em trai rất ghét cá.",
    theme: "rose",
  },
  {
    id: "p049",
    title: "Phó từ mức độ & Nが あります・わかります",
    subtitle: "よく・だいたい・すこし・あまり・ぜんぜん",
    type: "grammar",
    japanese: "おかねが あります。\nにほんごが わかります。\nこのえいがは ぜんぜん おもしろくないです。",
    romaji: "Okane ga arimasu. / Nihongo ga wakarimasu. / Kono eiga wa zenzen omoshirokunai desu.",
    translation: "Có tiền. / Hiểu tiếng Nhật. / Bộ phim này chẳng thú vị chút nào.",
    bullets: [
      "Khẳng định: よく／だいたい／すこし わかります; たくさん／すこし あります",
      "Phủ định: あまり／ぜんぜん わかりません／ありません",
      "すこし・あまり・ぜんぜん còn bổ nghĩa được cho tính từ",
    ],
    theme: "rose",
  },
  {
    id: "p050",
    title: "どうして・なぜ・なんで … から。",
    subtitle: "Hỏi & trả lời lý do",
    type: "grammar",
    japanese: "じかんが ありませんから、あさごはんを たべません。\nどうして あさごはんを たべませんか。…じかんが ありませんから。",
    romaji: "Jikan ga arimasen kara, asagohan o tabemasen. / Doushite asagohan o tabemasen ka. ... Jikan ga arimasen kara.",
    translation: "Vì không có thời gian nên tôi không ăn sáng. / Sao bạn không ăn sáng? ...Vì không có thời gian.",
    theme: "rose",
  },

  // ===== だい10か (p.51-55) =====
  {
    id: "p051",
    title: "だい10か",
    subtitle: "あります・います & vị trí",
    type: "title",
    japanese: "だい１０か",
    romaji: "Dai jukka",
    translation: "Bài 10",
    theme: "dark",
  },
  {
    id: "p052",
    title: "N1のN2(vị trí)",
    subtitle: "N1とN2の あいだ",
    type: "grammar",
    japanese: "つくえの した\nぎんこうの ちかく\nAさんと Bさんの あいだ",
    romaji: "Tsukue no shita / ginkou no chikaku / A-san to B-san no aida",
    translation: "Dưới bàn / gần ngân hàng / giữa anh A và anh B",
    theme: "dark",
  },
  {
    id: "p053",
    title: "N(địa điểm)に Nが あります・います",
    subtitle: "あります(vật) ／ います(người, động vật)",
    type: "grammar",
    japanese: "じむしょ(のなか)に ファクスが あります。\nおくじょうに イーさんが います。\nにわに にわとりが います。",
    romaji: "Jimusho (no naka) ni fakusu ga arimasu. / Okujou ni Ii-san ga imasu. / Niwa ni niwatori ga imasu.",
    translation: "Trong văn phòng có máy fax. / Trên sân thượng có anh Lee. / Trong sân có gà.",
    bullets: ["Phủ định: なにも ありません／だれも いません／どんなどうぶつも いません"],
    theme: "dark",
  },
  {
    id: "p054",
    title: "Đảo ngữ: Nは N(địa điểm)に あります・います",
    subtitle: "どこに あります／いますか。",
    type: "grammar",
    japanese: "ファクスは じむしょに あります。",
    romaji: "Fakusu wa jimusho ni arimasu.",
    translation: "Máy fax ở trong văn phòng.",
    theme: "dark",
  },
  {
    id: "p055",
    title: "Nと N ／ Nや N(など)",
    subtitle: "Liệt kê tất cả ／ liệt kê tiêu biểu",
    type: "grammar",
    japanese: "つくえのうえに おさらや ナイフが あります。\nつくえのうえに はしや おさらや ナイフなどが あります。",
    romaji: "Tsukue no ue ni osara ya naifu ga arimasu.",
    translation: "Trên bàn có đĩa, dao,...",
    theme: "dark",
  },

  // ===== だい11か (p.56-59) =====
  {
    id: "p056",
    title: "だい11か",
    subtitle: "Số lượng từ & tần suất",
    type: "title",
    japanese: "だい１１か",
    romaji: "Dai juuikka",
    translation: "Bài 11",
    theme: "indigo",
  },
  {
    id: "p057",
    title: "Số lượng từ",
    subtitle: "Số từ + trợ số từ, tùy đối tượng mà trợ số từ khác nhau",
    type: "grammar",
    japanese: "りんごを 4つ かいました。\n4かげつ にほんごを べんきょうします。",
    romaji: "Ringo o yottsu kaimashita. / Yon-kagetsu nihongo o benkyoushimasu.",
    translation: "Đã mua 4 quả táo. / Học tiếng Nhật 4 tháng.",
    theme: "indigo",
  },
  {
    id: "p058",
    title: "どのくらい・かかります・ぐらい",
    subtitle: "Bao lâu／mất, tốn／khoảng",
    type: "grammar",
    japanese: "どのくらい にほんごを べんきょうしますか。…4かげつ べんきょうします。\nがっこうから うちへ バスで どのくらい かかりますか。…30ぷん かかります。\nきょうしつに がくせいが 40にんぐらい います。",
    romaji: "Dono kurai nihongo o benkyoushimasu ka. / Gakkou kara uchi e basu de dono kurai kakarimasu ka. ... Sanjuppun kakarimasu.",
    translation: "Bạn học tiếng Nhật bao lâu? ...4 tháng. / Từ trường về nhà bằng xe buýt mất bao lâu? ...Mất 30 phút.",
    theme: "indigo",
  },
  {
    id: "p059",
    title: "Số lượng từ(thời gian)に số lần V ／ だけ",
    subtitle: "Tần suất ／ chỉ",
    type: "grammar",
    japanese: "1かげつに 2かい テニスを します。\nかいしゃに がいこくじんの かいしゃいんが 2人だけ います。",
    romaji: "Ikkagetsu ni nikai tenisu o shimasu. / Kaisha ni gaikokujin no kaishain ga futari dake imasu.",
    translation: "Mỗi tháng chơi tennis 2 lần. / Công ty chỉ có 2 nhân viên nước ngoài.",
    theme: "indigo",
  },

  // ===== だい12か (p.60-65) =====
  {
    id: "p060",
    title: "だい12か",
    subtitle: "So sánh hơn・kém・nhất",
    type: "title",
    japanese: "だい１２か",
    romaji: "Dai juunikka",
    translation: "Bài 12",
    theme: "emerald",
  },
  {
    id: "p061",
    title: "N1は N2より A",
    subtitle: "So sánh hơn (lấy N2 làm chuẩn)",
    type: "grammar",
    japanese: "くろいかばんは しろいかばんより たかいです。",
    romaji: "Kuroi kaban wa shiroi kaban yori takai desu.",
    translation: "Cặp đen đắt hơn cặp trắng.",
    theme: "emerald",
  },
  {
    id: "p062",
    title: "N1は N2ほど A(phủ định)",
    subtitle: "So sánh không bằng",
    type: "grammar",
    japanese: "ぎゅうにくは とりにくほど やすくないです。",
    romaji: "Gyuuniku wa toriniku hodo yasukunai desu.",
    translation: "Thịt bò không rẻ bằng thịt gà.",
    theme: "emerald",
  },
  {
    id: "p063",
    title: "N1とN2とどちらが A ですか。",
    subtitle: "Lựa chọn 1 trong 2",
    type: "grammar",
    japanese: "サッカーと やきゅうと どちらが おもしろいですか。…やきゅうのほうが おもしろいです。",
    romaji: "Sakkaa to yakyuu to dochira ga omoshiroi desu ka. ... Yakyuu no hou ga omoshiroi desu.",
    translation: "Bóng đá và bóng chày, cái nào thú vị hơn? ...Bóng chày thú vị hơn.",
    bullets: ["…どちらも A です。(chọn cả 2) ／ …どちらも Aくないです。(không chọn cả 2)"],
    theme: "emerald",
  },
  {
    id: "p064",
    title: "N(のなかで) N2がいちばん A です。",
    subtitle: "So sánh nhất",
    type: "grammar",
    japanese: "かぞくで ちちが いちばん せがたかいです。\nみかんと りんごと オレンジのなかで みかんが いちばん すきです。",
    romaji: "Kazoku de chichi ga ichiban se ga takai desu. / Mikan to ringo to orenji no naka de mikan ga ichiban suki desu.",
    translation: "Trong gia đình bố cao nhất. / Trong quýt, táo và cam, tôi thích quýt nhất.",
    theme: "emerald",
  },
  {
    id: "p065",
    title: "の (vai trò thay thế danh từ)",
    subtitle: "Tránh lặp lại danh từ đã nhắc trước đó",
    type: "grammar",
    japanese: "Cさんの くつは どれですか。…くろいのです。",
    romaji: "C-san no kutsu wa dore desu ka. ... Kuroi no desu.",
    translation: "Giày của bạn C là đôi nào? ...Đôi màu đen.",
    theme: "emerald",
  },

  // ===== だい13か (p.66-72) =====
  {
    id: "p066",
    title: "だい13か",
    subtitle: "ほしいです & Vたいです",
    type: "title",
    japanese: "だい１３か",
    romaji: "Dai juusankka",
    translation: "Bài 13",
    theme: "amber",
  },
  {
    id: "p067",
    title: "Nが ほしいです。",
    subtitle: "Muốn có N (danh từ)",
    type: "grammar",
    japanese: "わたしは 車(くるま)が ほしいです。",
    romaji: "Watashi wa kuruma ga hoshii desu.",
    translation: "Tôi muốn có xe hơi.",
    bullets: ["なにも ほしくないです。(không muốn gì cả)"],
    theme: "amber",
  },
  {
    id: "p068",
    title: "Vますたいです。",
    subtitle: "Muốn làm gì",
    type: "grammar",
    japanese: "ラーメンを（が）たべたいです。\n日本(にほん)へ いきたいです。",
    romaji: "Raamen o (ga) tabetai desu. / Nihon e ikitai desu.",
    translation: "Tôi muốn ăn mì ramen. / Tôi muốn đi Nhật.",
    bullets: [
      "V đi kèm を có thể thay thế bằng が; đi kèm trợ từ khác (で・に・と…) giữ nguyên",
      "なにを したいですか。／ なにも したくないです。",
    ],
    theme: "amber",
  },
  {
    id: "p069",
    title: "Lời mời không dùng たい・ほしい",
    subtitle: "Dùng Vませんか。／ いかがですか。",
    type: "grammar",
    japanese: "あした テニスを しませんか。\nおちゃは いかがですか。",
    romaji: "Ashita tenisu o shimasen ka. / Ocha wa ikaga desu ka.",
    translation: "Mai chơi tennis nhé? / Bạn dùng trà nhé?",
    theme: "amber",
  },
  {
    id: "p070",
    title: "N(địa điểm)へ Vに 行きます・来ます・帰ります",
    subtitle: "Đi/đến/về đâu để làm gì",
    type: "grammar",
    japanese: "ともだちのうちへ あそびに いきました。\nにほんへ かいものに きました。\nかぞくと きょうとへ おまつりに いきます。",
    romaji: "Tomodachi no uchi e asobi ni ikimashita. / Nihon e kaimono ni kimashita. / Kazoku to Kyouto e omatsuri ni ikimasu.",
    translation: "Đã đến nhà bạn chơi. / Đến Nhật để mua sắm. / Cùng gia đình đi lễ hội ở Kyoto.",
    theme: "amber",
  },
  {
    id: "p071",
    title: "N(の)べんきょう vs Nを べんきょうしに",
    subtitle: "So sánh danh từ mục đích và động từ mục đích",
    type: "grammar",
    japanese: "日本へ けいざいの べんきょうに きました。\n日本へ けいざいを べんきょうしに きました。",
    romaji: "Nihon e keizai no benkyou ni kimashita. / Nihon e keizai o benkyoushi ni kimashita.",
    translation: "Tôi đến Nhật để học kinh tế. (2 cách nói)",
    theme: "amber",
  },
  {
    id: "p072",
    title: "どこか・なにか & kính ngữ",
    subtitle: "Đâu đó, chỗ nào đó ／ Cái gì đó",
    type: "grammar",
    japanese: "あした どこか（へ）いきますか。\nおなかが すきましたから、なにか（を）たべましょう。",
    romaji: "Ashita dokoka (e) ikimasu ka. / Onaka ga sukimashita kara, nanika (o) tabemashou.",
    translation: "Mai bạn có đi đâu đó không? / Vì đói bụng nên ăn gì đó nhé.",
    bullets: ["ごちゅうもんは／ おすし: thể hiện sự kính trọng"],
    theme: "amber",
  },

  // ===== 第14課 (p.73-81) =====
  {
    id: "p073",
    title: "第14課",
    subtitle: "Nhóm động từ & thể て・た",
    type: "title",
    japanese: "だい１４か",
    romaji: "Dai juuyonka",
    translation: "Bài 14",
    theme: "rose",
  },
  {
    id: "p074",
    title: "Phân biệt nhóm động từ (3 nhóm)",
    subtitle: "Nhóm 1: cột い ・ Nhóm 2: cột え ・ Nhóm 3: します／来ます",
    type: "grammar",
    japanese: "いきます (I) ／ たべます (II) ／ べんきょうします (III)",
    bullets: [
      "Nhóm 1: trước ます là chữ thuộc cột い — vd: いきます",
      "Nhóm 2: trước ます là chữ thuộc cột え — vd: たべます",
      "Nhóm 3: します／Nします(danh động từ)／きます(来ます)",
      "Ngoại lệ nhóm 2 tuy trước ます là cột い: おきます(起)、みます、おります、あびます、きます(着)",
    ],
    theme: "rose",
  },
  {
    id: "p075",
    title: "Minh họa: 置きます (I) vs 起きます (II)",
    subtitle: "TRÍ vs KHỞI",
    type: "grammar",
    japanese: "置きます(おきます) — đặt, để (nhóm 1)\n起きます(おきます) — thức dậy (nhóm 2, ngoại lệ)",
    theme: "rose",
  },
  {
    id: "p076",
    title: "Minh họa: 着ます (II) vs 来ます (III)",
    subtitle: "TRƯỚC vs LAI",
    type: "grammar",
    japanese: "着ます(きます) — mặc đồ (nhóm 2, ngoại lệ)\n来ます(きます) — đến (nhóm 3)",
    theme: "rose",
  },
  {
    id: "p077",
    title: "Cách chia thể て・た — Nhóm 1",
    subtitle: "Theo đuôi trước ます",
    type: "grammar",
    japanese: "かいます → かって、かった\nよみます → よんで、よんだ\nかきます → かいて、かいた\nおよぎます → およいで、およいだ\nはなします → はなして、はなした\nいきます → いって、いった（ngoại lệ）",
    bullets: [
      "い・ち・り → って／った",
      "び・み・に → んで／んだ",
      "き → いて／いた； ぎ → いで／いだ； し → して／した",
    ],
    theme: "rose",
  },
  {
    id: "p078",
    title: "Cách chia thể て・た — Nhóm 2 & 3",
    subtitle: "Bỏ ます, thêm て／た",
    type: "grammar",
    japanese: "たべます → たべて、たべた\nおきます → おきて、おきた\nします → して、した\nべんきょうします → べんきょうして、べんきょうした\nきます(来) → きて、きた",
    theme: "rose",
  },
  {
    id: "p079",
    title: "Vてください。",
    subtitle: "Hãy, xin hãy… (yêu cầu, nhờ vả)",
    type: "grammar",
    japanese: "ボールペンで なまえを かいてください。\nどうぞ たくさん たべてください。\nすみませんが、みちを おしえてください。",
    romaji: "Boorupen de namae o kaite kudasai. / Douzo takusan tabete kudasai. / Sumimasenga, michi o oshiete kudasai.",
    translation: "Hãy viết tên bằng bút bi. / Mời ăn nhiều vào. / Xin hãy chỉ đường giúp tôi.",
    theme: "rose",
  },
  {
    id: "p080",
    title: "Vています。",
    subtitle: "Đang — hành động đang diễn ra",
    type: "grammar",
    japanese: "かんじを かいています。",
    romaji: "Kanji o kaite imasu.",
    translation: "Đang viết chữ Hán.",
    theme: "rose",
  },
  {
    id: "p081",
    title: "Vますましょうか。",
    subtitle: "…nhé/để tôi… cho (đề nghị giúp người nghe)",
    type: "grammar",
    japanese: "にもつを もちましょうか。\nはい（ええ）、おねがいします。／ いいえ、けっこうです。",
    romaji: "Nimotsu o mochimashou ka. / Hai (ee), onegaishimasu. / Iie, kekkou desu.",
    translation: "Để tôi xách hành lý giúp nhé? / Vâng, nhờ bạn nhé. / Không, cảm ơn (không cần).",
    theme: "rose",
  },

  // ===== 第15課 (p.82-85) =====
  {
    id: "p082",
    title: "第15課",
    subtitle: "Cấm đoán・xin phép・Vています",
    type: "title",
    japanese: "だい１５か",
    romaji: "Dai juugokka",
    translation: "Bài 15",
    theme: "dark",
  },
  {
    id: "p083",
    title: "Vてはいけません。／ だめです。",
    subtitle: "Cấm/không được làm 1 việc gì",
    type: "grammar",
    japanese: "このビルで しゃしんをとっては いけません。",
    romaji: "Kono biru de shashin o totte wa ikemasen.",
    translation: "Không được chụp ảnh trong tòa nhà này.",
    theme: "dark",
  },
  {
    id: "p084",
    title: "Vてもいいです。",
    subtitle: "Được phép làm — Vてもいいですか。= xin phép",
    type: "grammar",
    japanese: "このへやで でんわを つかっても いいです。\nたばこを すっても いいですか。",
    romaji: "Kono heya de denwa o tsukattemo ii desu. / Tabako o suttemo ii desu ka.",
    translation: "Có thể dùng điện thoại trong phòng này. / Tôi hút thuốc được không?",
    bullets: ["ええ（はい）、いいですよ。どうぞ。／ すみません。ちょっと…／ いいえ、（Vては）いけません。"],
    theme: "dark",
  },
  {
    id: "p085",
    title: "Vています。 (3 sắc thái)",
    subtitle: "Đang diễn ra ・ Trạng thái kết quả ・ Thói quen",
    type: "grammar",
    japanese: "にほんごを べんきょうしています。\nひとりで ベトナムに すんでいます。\nさくらだいがくで えいごを おしえています。",
    romaji: "Nihongo o benkyoushite imasu. / Hitori de Betonamu ni sunde imasu. / Sakura daigaku de eigo o oshiete imasu.",
    translation: "Đang học tiếng Nhật. / Sống một mình ở Việt Nam. (trạng thái) / Dạy tiếng Anh ở ĐH Sakura. (thói quen)",
    bullets: ["けっこんしています／すんでいます／もっています／しっています ⇔ しりません"],
    theme: "dark",
  },

  // ===== 第16課 (p.86-91) =====
  {
    id: "p086",
    title: "第16課",
    subtitle: "Nối câu Vて・Aくて・Aで",
    type: "title",
    japanese: "だい１６か",
    romaji: "Dai juurokka",
    translation: "Bài 16",
    theme: "indigo",
  },
  {
    id: "p087",
    title: "V1て V2て V3て…V",
    subtitle: "Liệt kê hành động theo trình tự thời gian (rồi)",
    type: "grammar",
    japanese: "にほんへきて、おすしをたべて、おはなみをしました。",
    romaji: "Nihon e kite, osushi o tabete, ohanami o shimashita.",
    translation: "Đến Nhật, ăn sushi rồi ngắm hoa.",
    theme: "indigo",
  },
  {
    id: "p088",
    title: "V1てから V2",
    subtitle: "Sau khi V1 mới V2",
    type: "grammar",
    japanese: "くにへ かえってから、にほんの かいしゃで はたらきます。",
    romaji: "Kuni e kaettekara, nihon no kaisha de hatarakimasu.",
    translation: "Sau khi về nước, tôi sẽ làm việc cho công ty Nhật.",
    theme: "indigo",
  },
  {
    id: "p089",
    title: "Aいくて ／ Aナ・Nで",
    subtitle: "Nối tính từ・danh từ (không nối 2 vế trái nghĩa)",
    type: "grammar",
    japanese: "ミラーさんは わかくて、あたまが よくて、おもしろいです。\nカリナさんは がくせいで、マリアさんは いしゃです。\nこのへやは せまいですが、きれいです。",
    romaji: "Miraa-san wa wakakute, atama ga yokute, omoshiroi desu. / Karina-san wa gakusei de, Maria-san wa isha desu.",
    translation: "Anh Miller trẻ, thông minh và thú vị. / Bạn Karina là sinh viên, bạn Maria là bác sĩ.",
    bullets: ["Trái nghĩa phải dùng が: このへやは せまいですが、きれいです。(KHÔNG dùng せまくて、きれいです)"],
    theme: "indigo",
  },
  {
    id: "p090",
    title: "N1は N2が A。",
    subtitle: "は đánh dấu chủ đề chính, が đánh dấu chủ ngữ mệnh đề phụ",
    type: "grammar",
    japanese: "かんじは よみかたが むずかしいです。",
    romaji: "Kanji wa yomikata ga muzukashii desu.",
    translation: "Chữ Hán khó ở cách đọc.",
    theme: "indigo",
  },
  {
    id: "p091",
    title: "どうやって",
    subtitle: "Hỏi trình tự/cách làm (bằng cách nào)",
    type: "grammar",
    japanese: "どうやって にほんごを べんきょうしますか。\nえいがを みて、しんぶんを よんで、おんがくを ききます。",
    romaji: "Douyatte nihongo o benkyoushimasu ka. / Eiga o mite, shinbun o yonde, ongaku o kikimasu.",
    translation: "Bạn học tiếng Nhật bằng cách nào? / Xem phim, đọc báo, nghe nhạc.",
    theme: "indigo",
  },

  // ===== 第17課 (p.92-96) =====
  {
    id: "p092",
    title: "第17課",
    subtitle: "Chia thể ない & giới hạn thời gian",
    type: "title",
    japanese: "だい１７か",
    romaji: "Dai juunanakka",
    translation: "Bài 17",
    theme: "emerald",
  },
  {
    id: "p093",
    title: "Cách chia thể ない",
    subtitle: "Nhóm 1: い→わ+ない ・ Nhóm 2: bỏ ます+ない ・ Nhóm 3: しない/こない",
    type: "grammar",
    japanese: "よみます → よまない\nかいます → かわない\nあります → ない（ngoại lệ）\nおしえます → おしえない\nします → しない\n来ます → こない",
    theme: "emerald",
  },
  {
    id: "p094",
    title: "Vないでください。",
    subtitle: "Xin đừng, đừng — yêu cầu người khác đừng làm gì",
    type: "grammar",
    japanese: "ここで しゃしんを とらないでください。",
    romaji: "Koko de shashin o toranaide kudasai.",
    translation: "Xin đừng chụp ảnh ở đây.",
    theme: "emerald",
  },
  {
    id: "p095",
    title: "Vなくてもいいです。",
    subtitle: "Không phải làm 1 việc gì đó cũng được",
    type: "grammar",
    japanese: "くつを ぬがなくても いいです。",
    romaji: "Kutsu o nuganakutemo ii desu.",
    translation: "Không cần cởi giày cũng được.",
    theme: "emerald",
  },
  {
    id: "p096",
    title: "N(thời gian)までに V ／ …まで",
    subtitle: "Trước… (hạn chót) ／ Đến…",
    type: "grammar",
    japanese: "きんようびまでに レポートを ださなければ なりません。\nこんしゅうは きんようびまで はたらきます。",
    romaji: "Kinyoubi made ni repooto o dasanakereba narimasen. / Konshuu wa kinyoubi made hatarakimasu.",
    translation: "Phải nộp báo cáo trước thứ Sáu. / Tuần này tôi làm việc đến hết thứ Sáu.",
    theme: "emerald",
  },

  // ===== 第18課 (p.97-102) =====
  {
    id: "p097",
    title: "第18課",
    subtitle: "Thể từ điển & khả năng",
    type: "title",
    japanese: "だい１８か",
    romaji: "Dai juuhakka",
    translation: "Bài 18",
    theme: "amber",
  },
  {
    id: "p098",
    title: "Cách chia thể từ điển",
    subtitle: "Nhóm 1: い→う ・ Nhóm 2: bỏ ます+る ・ Nhóm 3: する/くる",
    type: "grammar",
    japanese: "よみます → よむ\nおしえます → おしえる\nします → する\n来ます → くる",
    theme: "amber",
  },
  {
    id: "p099",
    title: "Nができます／Vること(が)できます",
    subtitle: "Có thể/biết làm gì",
    type: "grammar",
    japanese: "にほんごが できます。\nおよぐことが できます。",
    romaji: "Nihongo ga dekimasu. / Oyogu koto ga dekimasu.",
    translation: "Tôi biết tiếng Nhật. / Tôi biết bơi.",
    theme: "amber",
  },
  {
    id: "p100",
    title: "しゅみは N／Vることです。",
    subtitle: "Sở thích là…",
    type: "grammar",
    japanese: "わたしのしゅみは えいがです。\nわたしのしゅみは えいがを みることです。",
    romaji: "Watashi no shumi wa eiga desu. / Watashi no shumi wa eiga o miru koto desu.",
    translation: "Sở thích của tôi là phim ảnh. / Sở thích của tôi là xem phim.",
    theme: "amber",
  },
  {
    id: "p101",
    title: "V1るまえに、V2",
    subtitle: "Trước khi V1 thì V2 (V2 xảy ra trước V1 theo thời gian thực)",
    type: "grammar",
    japanese: "ねるまえに、ほんを よみます。\nしょくじのまえに、手を あらいます。\n5ねんまえに、にほんへ きました。",
    romaji: "Neru mae ni, hon o yomimasu. / Shokuji no mae ni, te o araimasu. / Gonen mae ni, nihon e kimashita.",
    translation: "Trước khi ngủ, tôi đọc sách. / Trước bữa ăn, rửa tay. / 5 năm trước, tôi đến Nhật.",
    theme: "amber",
  },
  {
    id: "p102",
    title: "なかなか… & ぜひ",
    subtitle: "Mãi mà không… ／ Nhất định",
    type: "grammar",
    japanese: "なかなか にほんへ いくことができません。\nぜひ にほんへ いきたいです。\nぜひ あそびに きてください。",
    romaji: "Nakanaka nihon e iku koto ga dekimasen. / Zehi nihon e ikitai desu.",
    translation: "Mãi mà không thể đi Nhật được. / Tôi nhất định muốn đi Nhật.",
    theme: "amber",
  },

  // ===== 第19課 (p.103-107) =====
  {
    id: "p103",
    title: "第19課",
    subtitle: "Kinh nghiệm & liệt kê hành động",
    type: "title",
    japanese: "だい１９か",
    romaji: "Dai juukyuukka",
    translation: "Bài 19",
    theme: "rose",
  },
  {
    id: "p104",
    title: "Vた ことが あります。",
    subtitle: "Đã từng làm gì (kinh nghiệm trong quá khứ)",
    type: "grammar",
    japanese: "すもうを みたことが あります。\nふじさんに のぼったことが ありません。",
    romaji: "Sumou o mita koto ga arimasu. / Fujisan ni nobotta koto ga arimasen.",
    translation: "Tôi đã từng xem đấu vật sumo. / Tôi chưa từng leo núi Phú Sĩ.",
    theme: "rose",
  },
  {
    id: "p105",
    title: "Vたり、Vたりします。",
    subtitle: "Liệt kê hành động tiêu biểu (làm…làm…)",
    type: "grammar",
    japanese: "やすみのひは テニスをしたり、さんぽに いったりします。\nそうじしたり、せんたくしたり しなければ なりません。",
    romaji: "Yasumi no hi wa tenisu o shitari, sanpo ni ittari shimasu.",
    translation: "Ngày nghỉ tôi hay chơi tennis, đi dạo...",
    theme: "rose",
  },
  {
    id: "p106",
    title: "Aく なります／ Aナ・Nに なります",
    subtitle: "Trở nên, trở thành (thay đổi trạng thái)",
    type: "grammar",
    japanese: "あつく なります。\nべんりに なります。\nいもうとは いしゃに なります。",
    romaji: "Atsuku narimasu. / Benri ni narimasu. / Imouto wa isha ni narimasu.",
    translation: "Trời trở nên nóng. / Trở nên tiện lợi. / Em gái sẽ trở thành bác sĩ.",
    theme: "rose",
  },
  {
    id: "p107",
    title: "そうですか ⇔ そうですね",
    subtitle: "Tiếp nhận thông tin mới ⇔ Đồng tình, thông cảm",
    type: "grammar",
    japanese: "そうですか。\nそうですね。",
    theme: "rose",
  },

  // ===== 第20課 (p.108-111) =====
  {
    id: "p108",
    title: "第20課",
    subtitle: "Tổng hợp thể ngắn (普通形)",
    type: "title",
    japanese: "だい２０か",
    romaji: "Dai nijukka",
    translation: "Bài 20",
    theme: "dark",
  },
  {
    id: "p109",
    title: "Bảng thể ngắn: Động từ & tính từ い",
    subtitle: "ます→る・ません→ない・ました→た・ませんでした→なかった",
    type: "grammar",
    japanese: "Vます→Vる／Vません→Vない／Vました→Vた／Vませんでした→Vなかった\nAいです→Aい／Aくないです→Aくない／Aかったです→Aかった／Aくなかったです→Aくなかった",
    theme: "dark",
  },
  {
    id: "p110",
    title: "Bảng thể ngắn: Aナ／N & thể て",
    subtitle: "です→だ・ではありません→ではない",
    type: "grammar",
    japanese: "Aナ/Nです→だ／ではありません→ではない／でした→だった／ではありませんでした→ではなかった\nVています→Vて(い)る／Vてください→Vて",
    theme: "dark",
  },
  {
    id: "p111",
    title: "Hội thoại thân mật & trợ từ có thể lược bỏ",
    subtitle: "を・へ・が・は có thể lược bỏ; で・に・から・まで・と thì không",
    type: "grammar",
    japanese: "おちゃを のむ？ …うん、のむ。／ ううん、のまない。\nあした ひま(だ)？ …うん、ひま(だよ)。／ ううん、ひまじゃない。",
    romaji: "Ocha o nomu? ... Un, nomu. / Uun, nomanai. / Ashita hima (da)? ... Un, hima (da yo).",
    translation: "Uống trà không? ...Ừ, uống. / Không, không uống. / Mai rảnh không? ...Ừ, rảnh.",
    theme: "dark",
  },

  // ===== 第21課 (p.112-116) =====
  {
    id: "p112",
    title: "第21課",
    subtitle: "普通形 + と思います・と言います",
    type: "title",
    japanese: "だい２１か",
    romaji: "Dai nijuuikka",
    translation: "Bài 21",
    theme: "indigo",
  },
  {
    id: "p113",
    title: "Thể thường + と おもいます。",
    subtitle: "Tôi nghĩ rằng…",
    type: "grammar",
    japanese: "あした あめが ふると おもいます。",
    romaji: "Ashita ame ga furu to omoimasu.",
    translation: "Tôi nghĩ mai trời sẽ mưa.",
    theme: "indigo",
  },
  {
    id: "p114",
    title: "「Câu」／thể ngắn + と いいます。",
    subtitle: "Nói rằng…",
    type: "grammar",
    japanese: "しゅしょうは らいげつ アメリカに いくと いいました。\nしゅしょうは「らいげつ アメリカに いきます」と いいました。",
    romaji: "Shushou wa raigetsu Amerika ni iku to iimashita.",
    translation: "Thủ tướng đã nói rằng tháng sau sẽ đi Mỹ.",
    theme: "indigo",
  },
  {
    id: "p115",
    title: "Thể ngắn(Aナ・Nだ) + でしょう。",
    subtitle: "Chắc là…phải không? (mong đợi sự đồng tình)",
    type: "grammar",
    japanese: "あした パーティーに いくでしょう。",
    romaji: "Ashita paatii ni iku deshou.",
    translation: "Chắc mai bạn sẽ đi tiệc nhỉ?",
    theme: "indigo",
  },
  {
    id: "p116",
    title: "Ví dụ mở rộng で／でも",
    subtitle: "とうきょうで … ／ ちょっと…でも",
    type: "grammar",
    japanese: "とうきょうで 日本と ブラジルの サッカーの しあいが あります。\nかいぎで なにか いけんを いいましたか。\nちょっと ビールでも のみませんか。",
    romaji: "Toukyou de Nihon to Burajiru no sakkaa no shiai ga arimasu. / Chotto biiru demo nomimasen ka.",
    translation: "Ở Tokyo có trận bóng đá giữa Nhật và Brazil. / Uống chút bia gì đó không?",
    theme: "indigo",
  },

  // ===== 第22課 (p.117-118) =====
  {
    id: "p117",
    title: "第22課",
    subtitle: "Mệnh đề bổ nghĩa danh từ",
    type: "title",
    japanese: "だい２２か",
    romaji: "Dai nijuunikka",
    translation: "Bài 22",
    theme: "emerald",
  },
  {
    id: "p118",
    title: "NのN／AいN／AナなN／V(thể ngắn)N",
    subtitle: "Mệnh đề đứng trước bổ nghĩa cho danh từ đứng sau",
    type: "grammar",
    japanese: "これは これから つかうほんです。\nわたしが うまれた ところは よこはまです。",
    romaji: "Kore wa korekara tsukau hon desu. / Watashi ga umareta tokoro wa Yokohama desu.",
    translation: "Đây là quyển sách sắp tới sẽ dùng. / Nơi tôi sinh ra là Yokohama.",
    theme: "emerald",
  },

  // ===== 第23課 (p.119-122) =====
  {
    id: "p119",
    title: "第23課",
    subtitle: "Vるとき・Vたとき・Vると",
    type: "title",
    japanese: "だい２３か",
    romaji: "Dai nijuusankka",
    translation: "Bài 23",
    theme: "amber",
  },
  {
    id: "p120",
    title: "Vる／Aい／Aな／Nの とき、…",
    subtitle: "Khi (mệnh đề trước chưa/sắp/đang diễn ra)",
    type: "grammar",
    japanese: "みちを わたるとき、くるまに きをつけます。",
    romaji: "Michi o wataru toki, kuruma ni ki o tsukemasu.",
    translation: "Khi băng qua đường, phải chú ý xe cộ.",
    theme: "amber",
  },
  {
    id: "p121",
    title: "Vるとき＝Vるまえに ・ Vたとき＝Vてから",
    subtitle: "Trước khi ・ Sau khi",
    type: "grammar",
    japanese: "うちへ かえるとき、ケーキを かいます。\nうちへ かえったとき、「ただいま」と いいます。",
    romaji: "Uchi e kaeru toki, keeki o kaimasu. / Uchi e kaetta toki, 'tadaima' to iimasu.",
    translation: "Trên đường về nhà (chưa về), mua bánh kem. / Khi (đã) về đến nhà, nói 'tôi về rồi'.",
    theme: "amber",
  },
  {
    id: "p122",
    title: "Vる と、…",
    subtitle: "Hễ…thì… (kết quả tất yếu)",
    type: "grammar",
    japanese: "このボタンを おすと、おつりが でます。",
    romaji: "Kono botan o osu to, otsuri ga demasu.",
    translation: "Bấm nút này thì tiền thối ra.",
    bullets: ["Không dùng と để rủ rê/ra lệnh ở vế sau (dùng V(ます)たいです／ませんか／てください thay thế)"],
    theme: "amber",
  },

  // ===== 第24課 (p.123-126) =====
  {
    id: "p123",
    title: "第24課",
    subtitle: "あげます・もらいます・くれます (nâng cao)",
    type: "title",
    japanese: "だい２４か",
    romaji: "Dai nijuuyonka",
    translation: "Bài 24",
    theme: "rose",
  },
  {
    id: "p124",
    title: "Sは 人に/を/と Vてあげます。",
    subtitle: "Làm giúp một hành động tốt cho người khác",
    type: "grammar",
    japanese: "わたしは きむらさんに ほんを かしてあげました。\nやまださんは たなかさんを えきで むかえてあげました。",
    romaji: "Watashi wa Kimura-san ni hon o kashite agemashita. / Yamada-san wa Tanaka-san o eki de mukaete agemashita.",
    translation: "Tôi đã cho anh Kimura mượn sách. / Anh Yamada đã ra ga đón giúp anh Tanaka.",
    theme: "rose",
  },
  {
    id: "p125",
    title: "Sは 人に Vてもらいます。",
    subtitle: "Nhờ/nhận được hành động tốt từ người khác",
    type: "grammar",
    japanese: "わたしは ちちに とけいを かってもらいました。\nきむらさんは やまださんに びょういんの でんわばんごうを おしえてもらいました。",
    romaji: "Watashi wa chichi ni tokei o katte moraimashita.",
    translation: "Tôi đã nhờ bố mua đồng hồ giúp.",
    theme: "rose",
  },
  {
    id: "p126",
    title: "Sは(わたしに) Vてくれます。",
    subtitle: "Người khác chủ động làm giúp cho mình/gia đình mình",
    type: "grammar",
    japanese: "かれは わたしに セーターを おくってくれました。\nみせの人は ははに おふろの はいりかたを せつめいしてくれました。",
    romaji: "Kare wa watashi ni seetaa o okutte kuremashita.",
    translation: "Anh ấy đã gửi tặng tôi áo len.",
    theme: "rose",
  },

  // ===== 第25課 (p.127-129) =====
  {
    id: "p127",
    title: "第25課",
    subtitle: "Câu điều kiện たら・ても — Bài tổng kết sơ cấp",
    type: "title",
    japanese: "だい２５か",
    romaji: "Dai nijuugokka",
    translation: "Bài 25",
    theme: "dark",
  },
  {
    id: "p128",
    title: "(もし) Vたら／Aかったら／Aナ・Nだったら",
    subtitle: "Nếu…thì… ／ Vたら còn mang nghĩa 'sau khi'",
    type: "grammar",
    japanese: "あめが ふったら、でかけません。\nやすかったら、あのみせで かいます。\nひまだったら、あそびに いきます。\n家へ かえったら、すぐ シャワーを あびます。",
    romaji: "Ame ga futtara, dekakemasen. / Yasukattara, ano mise de kaimasu. / Hima dattara, asobi ni ikimasu.",
    translation: "Nếu trời mưa thì tôi sẽ không ra ngoài. / Nếu rẻ thì tôi sẽ mua ở tiệm đó. / Nếu rảnh thì tôi sẽ đi chơi.",
    theme: "dark",
  },
  {
    id: "p129",
    title: "(いくら) Vても／Aくても／Aナ・Nでも",
    subtitle: "Dù…cũng… (trái với dự đoán thông thường)",
    type: "grammar",
    japanese: "（いくら）あめが ふっても、でかけます。",
    romaji: "(Ikura) ame ga futtemo, dekakemasu.",
    translation: "Dù (có) mưa cũng đi ra ngoài.",
    theme: "dark",
  },
];
